### ISSUE TITLE
Problem with query string appended to URLs

### ISSUE THREAD

**Issue by ciscoheat** [cgiffard/node-simplecrawler#101]
I'm crawling a quite simple site, and find that after redirects containing a query string, the query string is appended to the redirect URL and on the subsequent page. A typical debug log can look like this:

```
Redirect from http://localhost:3000/cart/add?sku=HR199 to 
{ protocol: 'http',
  host: 'localhost',
  port: '3000',
  path: '/vacations?sku=HR199',
  uriPath: '/vacations' }
```

The redirect should be going to `/vacations` without query, so the query string is taken from the first request. Another example with a non-redirect:

```
Fetched: http://localhost:3000/notify-me-when-in-season?sku=OC39
--- Found the following links at http://localhost:3000/notify-me-when-in-season?sku=OC39
http://localhost:3000/vendor/bootstrap.min.css?sku=OC39
http://localhost:3000/css/main.css?sku=OC39
http://localhost:3000/css/cart.css?sku=OC39
http://localhost:3000/img/logo.png?sku=OC39
http://localhost:3000/vendor/jquery-2.1.1.min.js?sku=OC39
http://localhost:3000/vendor/bootstrap.min.js?sku=OC39
http://localhost:3000/js/contact.js?sku=OC39
http://localhost:3000/js/cart.js?sku=OC39
---
```

Here the query is appended to all the links found on the page, which it shouldn't be.

Any ideas what's wrong?

**Comment by cgiffard** [comment]
That's very unusual indeed. I don't seem to be able to reproduce it! Would you be able to provide a small test case? (Sorry, I don't normally ask for that much!)

**Comment by ciscoheat** [comment]
Hi, I'll be offline for a week unfortunately, but if you have some time the whole project is available at https://github.com/ciscoheat/meadowlark

It's a little bit of work to set up since it's written in Haxe instead of js, but if you do you can test the above issue easily with `grunt tests`. If you don't have time I'll be back later with a test case!

**Comment by cgiffard** [comment]
Hi! This was apparently related to an old version of URI.js — and has since been corrected. Please let me know if the issue is still occurring! :)
