### ISSUE TITLE
Parent url's query parameters are added to every parsed url

### ISSUE THREAD

**Issue by timbowhite** [cgiffard/node-simplecrawler#103]
If a fetched page has query params, then every url detected and queued on the page has those query params added.

This is due to using an old URIjs version: https://github.com/medialize/URI.js/issues/113
Upgrading the URIjs version in package.json should fix this

**Comment by BrandonCouts** [comment]
I had this issue as well. I ended up doing a dirty hack, before I came and saw this:
uriURL = URI( URL );
uriURL = uriURL.absoluteTo(queueItem.url);
uriURL = uriURL.normalize();
if( origURL._parts.query === null ) uriURL._parts.query = null;
uriURL.build();
URL = uriURL.toString();

**Comment by cgiffard** [comment]
I updated the URI.js version last night. Are you still having the issue?

**Comment by cgiffard** [comment]
I believe this is now fixed. :)

**Comment by BrandonCouts** [comment]
This is fixed. tyvm
