### ISSUE TITLE
Only crawl one page

### ISSUE THREAD

**Issue by gogson** [cgiffard/node-simplecrawler#109]
Hi !

I'd like to crawl a single page from it's URI, without going any further.

I have the following website structure:
```
www.myweb.com (home page, containing links to page1, 2, 3)
www.myweb.com/page1 (page containing PDF links + links to page 2,3)
www.myweb.com/page2 (page containing PDF links + links to page 1,3)
www.myweb.com/page3 (page containing PDF links + links to page 1,2)
```

I want to be able to download all PDF files included in one page, not the entire website. Something like "download me all PDF files included in page 1 and 3".

My problem is that if I call the plugin with the www.myweb.com/page1 URI, it will fetch all PDFs, and then automatically go to page 2, do the same, and then to page 3....

I tried the maxDepth 0 and 1 value but it does not seems to work.

How can I prevent the plugin from crawling the entire website ?

I'm using the plugin like this:

```
var currentCrawler = crawler.crawl("www.myweb.com/page1");
currentCrawler.maxDepth = 1;
currentCrawler.on("fetchcomplete", function(queueItem, responseBuffer, response) { ... });
```

**Comment by cgiffard** [comment]
Hi! I notice you closed this before I got a chance to look at it — did you manage to resolve your query?

**Comment by gogson** [comment]
Hi !
I didn't know if my question was clear and understandable.

I finally managed to make it work using `addFetchCondition`.
Resources not matching the right path aren't added in queue.

You can check the code, it's a free [tool](https://github.com/gogson/node-vgmusic-downloader) for downloading all MIDI files from VGMusic.com.
