### ISSUE TITLE
requestLatency, requestTime & downloatTime

### ISSUE THREAD

**Issue by unr3al011** [cgiffard/node-simplecrawler#110]
Hello,
can you please say a few words about requestLatency? What exactly does that mean?

I am aware that requestTime is the time in ms that the whole request took.

But what does requestLatency and downloatTime mean?

**Comment by cgiffard** [comment]
requestLatency is the time taken until the headers are returned (in practice, this is essentially the time to first byte.) downloadTime is the time taken just to download the data in the response body.
