### ISSUE TITLE
Implementing a link checker

### ISSUE THREAD

**Issue by davidsinclair** [cgiffard/node-simplecrawler#114]
Hi,

First off I have to say I really like node-simplecrawler - good work! 

I want to implement a link checker for the site I am working on and using it has gotten me 95% of the way there but I am stuck getting the last little bit working. What I want to do is check all links on the site for 404's and redirects.  We feed the results into our custom content management system so that content authors can fix the broken links it finds.

However, we want to verify external links but not to actually go an and crawl that site.  It seems that simplecrawler will not fetch the external links unless I set filterByDomain to false.  But if I do that then it starts to also crawl those sites.  I do not want to set a fixed depth because I want to ensure our whole site gets crawled.  

I have tried implementing my own link discovery but when I do this the queueItems do not have a referrer set.  I really need to know the referrer in order to report the link back to our system.

Any ideas?  For now I have just added an if statement to your discoverResources function that returns an empty array for external sites.  Is there a better way for me to do this? 

Many thanks for any guidance you can give me,

David

**Comment by cgiffard** [comment]
Hi! This is a good use case — thanks for filing an issue. I'm pretty busy for a couple of days, so I'll have a think about this and get back to you on the weekend. :)

**Comment by davidsinclair** [comment]
Hi,

Have you had a chance to think about how this might be handled?  I would be happy to implement the solution and submit a pull request if you could suggest the approach you think fits best.  

Thanks,

David

**Comment by cgiffard** [comment]
Hey — if you're still interested, the feature is being bashed out in PR #74 (https://github.com/cgiffard/node-simplecrawler/pull/74) — but I've asked for a test to be added. I'll pick it up myself if required — seems a lot of people want this feature. :)

**Comment by fredrikekelund** [comment]
This ticket is an oldie, but I guess what could solve this use case would be to pass the current queueItem to fetch conditions. With that, I could tell where the resource I'm looking at has been discovered, and filter it based on that. So I set filterByDomain to false, but avoid any resources on the second site that were in fact discovered on the second site.

**Comment by fredrikekelund** [comment]
The feature I suggested was merged in #217 and released in 0.6.2
