### ISSUE TITLE
Error: "name" and "value" are required for setHeader()

### ISSUE THREAD

**Issue by mattfordham** [cgiffard/node-simplecrawler#116]
I am getting this error with the simple test below...

`crawler = Crawler.crawl("http://example.com")`

Any ideas?

**Comment by federicomaffei** [comment]
+1 @mattfordham - I believe this issue has already been fixed here https://github.com/cgiffard/node-simplecrawler/pull/107 but the fixed version is not available via npm. @cgiffard could you kindly publish the new version, if possible? Thanks a lot.

**Comment by aesopwolf** [comment]
+1 on this

**Comment by mpgarate** [comment]
+1 I am experiencing this as well.

**Comment by krisanalfa** [comment]
+1 Me too

**Comment by federicomaffei** [comment]
@all here, found a workaround to this issue. Adding an empty `Referer` header to `crawler.customHeaders` will prevent this Error to be thrown.

**Comment by cgiffard** [comment]
Sorry, this is me being a really lame maintainer and not publishing the fixed version to npm—I'll get that sorted now. :)

**Comment by cgiffard** [comment]
This should be fixed now! :)

**Comment by federicomaffei** [comment]
@cgiffard yes! tested the updated module in production and working just fine :)

**Comment by cgiffard** [comment]
Fantastic. :)
