### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by jamalsoueidan** [cgiffard/node-simplecrawler#12]
var Crawler = require("simplecrawler").Crawler;

var myCrawler = new Crawler("http://www.google.com","/",80,300);

myCrawler.on("fetchcomplete",function(queueItem, responseBuffer, response) {
    console.log("I just received %s (%d bytes)",queueItem.url,responseBuffer.length);
    console.log("It was a resource of type %s",response.headers['content-type']);
});

myCrawler.start();

I'm missing something?

**Comment by durz** [comment]
@cgiffard Could you explain why removing `http://` makes crawling work? I spent a long time trying to get the crawler to work in advanced mode (simple mode `Crawler.crawl("http://example.com")` worked fine) and nothing worked until I came across your comment to remove the `http://`.

Also, all your examples in the documentation included `http://`.

**Comment by cgiffard** [comment]
@durz Good point — documentation issue. I'll make a point of cleaning it up. :)
