### ISSUE TITLE
Why does crawling www.cnn.com doesn't work?

### ISSUE THREAD

**Issue by yosiweinreb** [cgiffard/node-simplecrawler#121]
I am debating between this module and its rivals, i definitely liked this module interface and functionality the most, but while testing few sites i saw that crawling cnn didn't work. (simply returns empty queue)

Is there any reason for that?

Thanks

**Comment by yosiweinreb** [comment]
alright so i found the issue,
for those who wonder..
www.cnn.com does a 302 redirect to edition.cnn.com, and the crawler does not fetch 302.

**Comment by cgiffard** [comment]
Yep, that's normal behaviour—sorry it caused you some trouble. Perhaps I should make it clearer how this works in the documentation. :)
