### ISSUE TITLE
Need help to getting response statuse code - simplecrawler

### ISSUE THREAD

**Issue by shekarls** [cgiffard/node-simplecrawler#122]
Hi,
       I am new to node & JS, i was trying out this tool basically to find 404/500 on a page url.

below is my code snippet which doesnt print status code & also need atleast 1 level of depth to check for 404/500.

```js
var Crawler = require("../lib");
var url = "www.testerqa.com";
  
 var myCrawler = new Crawler(url);
  myCrawler.initialProtocol = "https";
 myCrawler.interval = 10000; // Ten seconds
myCrawler.maxConcurrency = 1;
myCrawler.maxDepth = 1;

console.log("STARTING");
myCrawler.on("fetchcomplete",function(queueItem, responseBuffer, response){
		console.log("Completed fetching resource:",queueItem.url);
                console.log((response.statuscode == 404) || (response.statuscode == 500));
	});
	
	myCrawler.start();
```

i don't see anything running in the console, is there a way it can print url and corresponding status code next to it.

Thanks
Chandra

**Comment by cgiffard** [comment]
Hi — thanks for your query.

If you want to see the status code for any item, regardless of what it is, you'll need to use the `fetchheaders` event. Requests which return responses other than ~200 are not downloaded, so they will not fire `fetchcomplete`. Other events might be useful for you too — you might just want to listen on `fetch404` and `fetcherror` to see 400 and 500 series responses.

The whole list of events is documented here. I encourage you to read it. :) 

https://github.com/cgiffard/node-simplecrawler#events

**Comment by shekarls** [comment]
When i see maxdepth = 0, still it crawls thru multiple links which are not on the current page.
is my implementation in sync with expected.


var Crawler = require("../lib");
Crawler.initialProtocol = "https";
Crawler.maxDepth = 0;

  var url = "https://www.rediff.com";
  

Crawler.crawl(url, function(queueItem) {
	
console.log("Completed fetching resource:",queueItem.url);
});
