### ISSUE TITLE
Special characters in buffer become unknown

### ISSUE THREAD

**Issue by BenChirlin** [cgiffard/node-simplecrawler#130]
Hello. I've been using simplecrawler to great success crawling our old archive site but I just noticed that the HTML I'm getting back out has all special characters (ä, à, etc.) converted into unknowns: � a.k.a `&#xFFFD;`.

My code for getting the HTML is straight forward. 

```
// On complete, if the URL matches our scrape rules add content to DB
spider.on( 'fetchcomplete', function( queueItem, responseBuffer, response ) {
		console.log( responseBuffer.toString().trim() );
} );
```

I've tried both `ascii` and `utf8` with my `toString` but neither translates the characters correctly. How do I preserve my special entities in the HTML? Thank you!

**Comment by fredrikekelund** [comment]
I had a similar problem, which turned out to be caused by the fact that the web page I was retrieving wasn't actually UTF-8 encoded. I don't know if this is the same problem you're having, but it's worth a shot if you're still interested.

I used `iconv-lite` to convert the response buffer content to UTF-8. Here's an example:
```js
var iconv = require("iconv-lite");


/**
 * Decode string buffer based on a Content-Type header. Meant for HTTP responses.
 * @param  {Buffer} buffer
 * @param  {String} [contentTypeHeader] - Eg. "text/html; charset=ISO-8859-1"
 * @return {String}
 */
var decodeResponse = function (buffer, contentTypeHeader) {
	contentTypeHeader = contentTypeHeader || "";

	var encoding = contentTypeHeader.split("charset=")[1] || contentTypeHeader;
	encoding = (iconv.encodingExists(encoding)) ? encoding : "utf-8";

	return iconv.decode(buffer, encoding);
};
```

And this is how I used it in action:
```js
crawler.on("fetchcomplete", function (queueItem, responseBuffer, response) {
	var body = decodeResponse(responseBuffer, response.headers["content-type"]),
		$ = cheerio.load(body);
});
```

**Comment by BenChirlin** [comment]
Thanks! After a bit more searching I too came across `iconv-lite` and it's working well for encoded characters. Looks like it even fixes some that broken on the pages I'm crawling!
