### ISSUE TITLE
Ignoring Max Depth

### ISSUE THREAD

**Issue by BenChirlin** [cgiffard/node-simplecrawler#131]
Hi. I was wondering if there's a way to have a set max depth but then have that ignored for certain types of URLs. I saw the `fetchWhitelistedMimeTypesBelowMaxDepth` but the documentation seems to imply this is only applicable to assets and not actual URLs in the page.

Specifically I want to crawl my site from an origin request to a given depth but want to ignore that depth with pagination links on pages to ensure the spider will crawl an entire paginated post and not cut off after a certain number of pages due to `maxDepth`. 

For instance, if `spider.maxDepth = 3;` and the spider is on a page `www.mysite.com/2014/06/astory.html`, a depth 3 from it's origin request. Is there a way to ensure the spider will continue to crawl a link `www.mysite.com/2014/06/astory.html?pg=2` even though it's already at its `maxDepth`?

Thank you!

**Comment by BenChirlin** [comment]
After a quick dive into the source it looks like the [`fetchWhitelistedMimeTypesBelowMaxDepth`](https://github.com/cgiffard/node-simplecrawler/blob/master/lib/crawler.js#L344) property only checks an internal list of type options. I'll make a pull request with that list being a variable which defaults to the current configuration.

**Comment by fredrikekelund** [comment]
The `fetchWhitelistedMimeTypesBelowMaxDepth` setting is a bit weird to me... I think the best way to accomplish what you're after would be to provide the current queueItem to all fetch conditions. That would enable the developer to determine whether to fetch the next resource based on the current depth.

I realize this ticket hasn't been active in a while, but I'll see what I can do about submitting a PR for this!

**Comment by BenChirlin** [comment]
Yeah pretty old. I already finished my project but I ended up forking the repo, adding an `ignoreDepth` option for a specific regex, and managed it that way. I submitted a PR but the manager of the repo said he didn't feel like it added enough utility but I'm glad to have tried to contribute (and got my project finished!).

**Comment by cgiffard** [comment]
I like the idea of making the queueItem available to fetch conditions. Bear in mind that it won't have much data in it at that early stage. (I think in the life cycle of where the fetch condition is executed, the queueItem hasn't even been created yet.)

**Comment by cgiffard** [comment]
Generally speaking I think a lot of people's requests centre around specific rules for what is fetched and what isn't — and having a more flexible mechanism to allow them to write those rules would both satisfy their requirements as well as keep a lot of crazily complex and highly specific logic out of simplecrawler core.

**Comment by fredrikekelund** [comment]
Looking at the code, I realize that depth is already one of the properties being passed to fetch conditions in the URL object. Maybe we ought to pass just the depth property as a second argument to avoid confusion.

I'm thinking it might be a good idea to complement fetch conditions with a new concept called something like download conditions. They would work the same way as fetch conditions, but be called once the initial response has been received. At that point there's not only a more complete queueItem, but also response headers available. Combining those two concepts should allow for quite a lot of flexibility, but also expose a pretty succinct API to the developer (and we would be able to drop `fetchWhitelistedMimeTypesBelowMaxDepth`).

Thoughts?

**Comment by fredrikekelund** [comment]
A solution like that would also address the use case that @rolfen is looking for in #188

**Comment by cgiffard** [comment]
I feel like this issue has been addressed by #217 — are we good to close, or am I mistaken?

**Comment by fredrikekelund** [comment]
You're probably right @cgiffard, I'll close this and open a separate issue for the download conditions idea
