### ISSUE TITLE
NTLM Authentication

### ISSUE THREAD

**Issue by HaaseIT** [cgiffard/node-simplecrawler#134]
Hi,
I wondered, if it would be possible to add NTLM Authentication (and possibly Digest), maybe using this node.js module:
https://github.com/SamDecrock/node-http-ntlm

I would greatly appreciate having the possibility to authenticate using NTLM.

My best regards
Marcus

**Comment by fredrikekelund** [comment]
Hi, sorry about the very late response on this one! I haven't worked with NTLM, but from a quick glance at the documentation for node-http-ntlm, it looks like it only needs to set a custom Authorization header, no special HTTP agents or anything. Adding such a header to simplecrawler is easy.

Basically it would look something like this:
```js
var ntlm = require('httpntlm').ntlm;
var Crawler = require('simplecrawler');

var options = {
    url: "https://someurl.com",
    username: 'm$',
    password: 'stinks',
    workstation: 'choose.something',
    domain: ''
};

var type1msg = ntlm.createType1Message(options);
var crawler = new Crawler("www.example.com");

crawler.customHeaders.Authorization = type1msg;
```

@HaaseIT would this solve your problem?

**Comment by fredrikekelund** [comment]
Closing this ticket for now since I believe the solution outlined above to lay out a good path for solving this. However, since I haven't worked with NTLM I might be wrong, let me know if that's the case @HaaseIT!
