### ISSUE TITLE
The web-programming curse of the Irish: M'name is O'Neal m' boy.

### ISSUE THREAD

**Issue by BrandonCouts** [cgiffard/node-simplecrawler#140]
So like a O'Neal.jpeg terminates the url detection early. Upon inspection this is because the regex doesn't try to match the opening quote with an identical closing quote. I added another discover rule to help solve this problem, though this is at the cost of more processing. I'm not that clever with regex, but I reckon this can be turned into a single rule again.

```javascript
	crawler.discoverRegex = [
		/(\shref\s?=\s?|\ssrc\s?=\s?|url\()([^\"\'\s>\)]+)/ig,
		/(\shref\s?=\s?|\ssrc\s?=\s?|url\()["]([^"]+)/ig,
		/(\shref\s?=\s?|\ssrc\s?=\s?|url\()[']([^']+)/ig,
		/http(s)?\:\/\/[^?\s><\'\"]+/ig,
		/url\([^\)]+/ig,
		/^javascript\:[a-z0-9\$\_\.]+\(['"][^'"\s]+/ig
	];
```

**Comment by BrandonCouts** [comment]
Also is there a reason why: 
/http(s)?\:\/\/[^?\s><\'\"]+/ig

Doesn't capture url's with queries in them?

**Comment by BrandonCouts** [comment]
```Javascript
crawler.discoverRegex = [
	/(\shref\s?=\s?|\ssrc\s?=\s?|url\()([^\"\'\s>\)]+)/ig,
	/(\shref\s?=\s?|\ssrc\s?=\s?|url\()((["][^"]+)|(['][^']+))/ig,
	/http(s)?\:\/\/[^\s><\'\"]+/ig,
	/url\([^\)]+/ig,
	/^javascript\:[a-z0-9\$\_\.]+\(['"][^'"\s]+/ig
];
```
I was wondering if you might comment about maybe getting this into the source. It seems to me this would be pretty straight forward change? The discovery regex needs the "?" I believe so the crawler can stripe it later as well? What are your thoughts on this?

**Comment by fredrikekelund** [comment]
@BrandonCouts can we close this?

**Comment by BrandonCouts** [comment]
Yup
