### ISSUE TITLE
Download resources with a specific header

### ISSUE THREAD

**Issue by magano227** [cgiffard/node-simplecrawler#141]
I've been using simplecrawler and it is awesome, thank you.
I've been trying to remove items from the queue and failing, what I want to do is when the headers of the queued files fetched, check the content-type and download only the ones I want. Is there any simple way of doing that? (I just want to download html, css and js files)
Thank you so much.

**Comment by BrandonCouts** [comment]
You want to use:
```Javascript 
spider.addFetchCondition( function( url ){ 
    return ! url.path.match( /\.gif/i );   // Ignore all .gifs
});
```

**Comment by BrandonCouts** [comment]
or inversely:
```Javascript
spider.addFetchCondition( function( url ){ 
    return url.path.match( /(\.html|\.css|\.js/i); // Match all html, css, and js files.
});
```

Sorry I should have thought about it a bit before. When I run the crawler I tend to run it to be inclusive, rather than exclusive.

**Comment by magano227** [comment]
That sounded like a good option for me at first but then I figured out that some files don't have any extension and in that case I won't be able to download them, that's why I was looking for a different solution.
Thank you anyway

**Comment by cgiffard** [comment]
@magano227 Are you still in need of a solution for this problem? Are you looking to *fetch* only resources with a particular header?

**Comment by fredrikekelund** [comment]
Only downloading HTML, CSS and JS files is the default so long as you flip `downloadUnsupported` to false, that option looks at the content-type header. The content types that are downloaded are stored in `crawler.supportedMimeTypes`.

**Comment by fredrikekelund** [comment]
Closing this since simplecrawler does have support for excluding resources based on their Content-Type header. Let us know if you're having more trouble, @magano227!
