### ISSUE TITLE
Fetching resource problem

### ISSUE THREAD

**Issue by magano227** [cgiffard/node-simplecrawler#143]
Well, I was crawling a website and suddenly the crawler stopped.
This is the url that is giving me problems: http://wineexplorer.brancottestate.com/assets/images/share_fb.jpg
I've been trying to fix this but I can't because it fetches the headers but not the body and so I can't move on.
Any help?

EDIT: This one is also stopping the crawler: http://wineexplorer.brancottestate.com/assets/dist/index.js

EDIT2: Nevermind, it was a problem with the website.

**Comment by cgiffard** [comment]
Hey @magnao227 — if this is still an issue please just reopen the ticket. (Apologies for the delay in my response.)
