### ISSUE TITLE
Crawler stops after redirect

### ISSUE THREAD

**Issue by teawithfruit** [cgiffard/node-simplecrawler#145]
I'm using simplecrawler for a project.
One of the websites to crawl have a redirect from the entry domain. Similar like when you type http://www.microsoft.com and you will get to http://www.microsoft.com/en-us/default.aspx.
In my opinion the redirected url should be added for crawling to the queue but the crawler stops, if the the entry domain is a redirect.

Here you can see my crawler code.
```javascript
var theCrawler = simplecrawler.crawl('http://www.microsoft.com')
.on("fetchcomplete", function(queueItem, responseBuffer, response) {
  console.log('fetchcomplete: ' + queueItem.url);
})
.on("fetchredirect", function(queueItem, parsedURL, response) {
  console.log('fetchredirect: ' + queueItem.url);
})
.on("fetch404", function(queueItem, response) {
  console.log('fetch404: ' + queueItem.url);
})
.on("fetcherror", function(queueItem, response) {
  console.log('fetcherror: ' + queueItem.url);
})
.on("queueadd", function(queueItem, responseBuffer, response) {
  console.log('queueadd: ' + queueItem.url);
})
.on("discoverycomplete", function(queueItem, resources) {
  console.log('discoverycomplete: ' + queueItem.url);
})
.on("complete", function() {
  console.log("complete");
});
```

Is this a known problem, or am i doing something wrong?

**Comment by fredrikekelund** [comment]
If the entry domain redirects to a different domain, the crawler won't add that URL unless you've added the new domain to `crawler.domainWhitelist` or have permitted the crawler to continue on any domain (by default simplecrawler will only crawl the initial domain, with the exception of any www subdomain). Redirects between pages on the same domain should be added correctly. Your code seems to work as expected (but I suspect you were trying to crawl a different domain than microsoft.com).

If you want to allow initial redirects to a different domain, you could add some custom logic that is triggered on fetchredirect events. This example checks if this was the initial request, and in that case adds the hostname of the new URL to the crawler's domain whitelist.

```js
crawler.on("fetchredirect", function (queueItem, parsedUrl, response) {
	var url = require("url");

	if (crawler.queue.length === 1) {
		crawler.domainWhitelist.push(url.parse(parsedUrl).hostname);
	}
})
```
