### ISSUE TITLE
Crawler failing to crawl

### ISSUE THREAD

**Issue by DavidFH** [cgiffard/node-simplecrawler#146]
Crawler is failing on this website. Only finds one page and none of the rest. Any idea as to why?

http://www.doosanbabcock.com/

**Comment by cgiffard** [comment]
There's no links on the page to pick up — everything else appears in a script, which simplecrawler does not evaluate. My recommendation is to queue a sub resource you know works, or write your own discovery function that can parse the big script block. See `crawler.discoverResources` in the documentation. :)
