### ISSUE TITLE
Crawler.stop() is undefined

### ISSUE THREAD

**Issue by iamso** [cgiffard/node-simplecrawler#147]
Hi 
I use the simplecrawler in Simple Mode. I can start it by calling Crawler.crawl(url).on(...
On fetchcomplete I push the processed results to a client app through a websocket.
Now if someone starts crawling a really large site and decides to abort it, I want to be able to stop the crawling process, but when I call Crawler.stop(), I get `TypeError: undefined is not a function`.

How can I stop the crawler completely?

Here is the code I use (it's Coffeescript)
```coffeescript
Crawler = require "simplecrawler"

Crawler.crawl url
  .on "fetchcomplete", (item) ->
    # do something
    
  .on "complete", ->
    # do something else

# to test it I called Crawler.stop() after a timeout, but it seems to be undefined
setTimeout ( ->
  Crawler.stop()
  console.log 'stopped'
), 4000
```

Thanks in advance
Steve

**Comment by cgiffard** [comment]
Hi Steve —

In this case, `Crawler` (with a capital C) is the constructor for simplecrawler. `Crawler.crawl` returns an *instance* of `Crawler`, which has the method required. So, you can do this:

```coffee
Crawler = require "simplecrawler"

myCrawler = Crawler.crawl url
  .on "fetchcomplete", (item) ->
    # do something

  .on "complete", ->
    # do something else

# to test it I called Crawler.stop() after a timeout, but it seems to be undefined
setTimeout ( ->
  myCrawler.stop()
  console.log 'stopped'
), 4000
```

Please let me know how that goes for you — and don't hesitate to ask if you require any further help. I'm pretty slow about following up issues but I'll do my best. :)

**Comment by iamso** [comment]
Perfect. Thanks.
