### ISSUE TITLE
How to copy same DOM element text?

### ISSUE THREAD

**Issue by 6pm** [cgiffard/node-simplecrawler#148]
I need write some text (name and price) on page from my shop, not all files. How do it?

**Comment by fredrikekelund** [comment]
I think you might need to clarify the question a bit. Do you want to save details from just some pages in you web shop or do you want to actually edit live web pages? The first case can be accomplished easily, the second case isn't really something you likely would want to use a crawler to do.

**Comment by cgiffard** [comment]
If you're just looking to scour your site and extract individual element text and data, I recommend using [Cheerio](https://www.npmjs.com/package/cheerio). Simply use cheerio.load() on the result passed to you via `fetchcomplete` and you can extract element values. Like this:

```js
crawler.on("fetchcomplete", function(queueItem, response) {
    if (queueItem.stateData.contentType.match(/text/i)) {
        var $ = cheerio.load(response),
            itemText = $(".shopitem h1").text(),
            itemPrice = $(".shopitem .price").text();
    }
});
````
