### ISSUE TITLE
queueItem.stateData.contentLength always 16777216

### ISSUE THREAD

**Issue by unr3al011** [cgiffard/node-simplecrawler#150]
Hello,
after crawling some different pages i always end up with a contentLength of 16777216.

Is this a bug or is there anything to configure for proper contentLength?

**Comment by cgiffard** [comment]
Hi — I believe that's a problem where your server may not be disconnecting, does not send a correct content-length header, and/or continuously sends data. The '16777216' is the default maximum payload size simplecrawler will fetch.

Could you send through some example URLs so I can verify this isn't a bug on my end?

Cheers.
