### ISSUE TITLE
crawler cannot finish

### ISSUE THREAD

**Issue by waitingkuo** [cgiffard/node-simplecrawler#152]
This is my sample code, but it runs endlessly

      var Crawler = require("simplecrawler");
   
      Crawler.crawl("http://www.pureunfoldment.com")
       .on("fetchcomplete", function(queueItem){
        console.log("Completed fetching resource:", queueItem.url);
      });

**Comment by BrandonCouts** [comment]
Add this to your program: 
	.on("complete", function() {
		console.log("complete");
	});

**Comment by waitingkuo** [comment]
normally, the program exits correctly. But with this domain, even that I added the handler for the complete event, it still didn't end.

**Comment by BrandonCouts** [comment]
Thats strange, I was able to get the crawler to return.
![capture](https://cloud.githubusercontent.com/assets/7916642/9060385/3eb8539a-3a81-11e5-944f-f98391fbb3c8.PNG)

**Comment by waitingkuo** [comment]
I'm using Mac and node 0.12.4. is my environment different?

**Comment by BrandonCouts** [comment]
I installed the latest node(0.12.4) just to confirm. Still runs to completion. 
Using: 
Windows 7 
node.js (0.12.4)
simplecrawler v 0.5.2 (via npm)

**Comment by cgiffard** [comment]
Hi @waitingkuo — I've updated the core repo to 0.5.3, which is available on npm. Are you still having the issue?

**Comment by fredrikekelund** [comment]
I just published simplecrawler 0.6.1. If you were experiencing this issue, please give it a try!
