### ISSUE TITLE
set response to queueItem

### ISSUE THREAD

**Issue by raintears** [cgiffard/node-simplecrawler#155]
hi! 
i was trying to check if the page have been downloaded and saved in my db, then i will just get the content from my db, set it to the queueItem, stop the fetch from the website, and let the crawler parse the links in the content and queue for the next fetch. But I can't find a way to do so.

i tried checking during the fetchstart event and queueadd event but the crawler continues to fetch from the website.

any help would be appreciated please!

**Comment by cgiffard** [comment]
Hi @raintears — you can use the `crawler.stop()` and `crawler.start()` methods to make it wait for you while you check your DB.
