### ISSUE TITLE
Crawler Still Fetching Resources past maxDepth

### ISSUE THREAD

**Issue by russelltaylor05** [cgiffard/node-simplecrawler#157]
Can't for the life of me figure out why the crawler keeps fetching resources past the Max Depth. Also, I'm seeing the events `fetchheaders` and `fetchstart`, but the `fetchcomplete` event never get fired. 

My crawler takes forever to finish because it fetching a ton of resources past my specified depth. Any thoughts?`

```javascript
var links = [];
var myCrawler = new Crawler("cssmenumaker.com");

myCrawler.interval = 200;
myCrawler.maxConcurrency = 2;
myCrawler.maxDepth = 1;
myCrawler.timeout = 1000;
myCrawler.fetchWhitelistedMimeTypesBelowMaxDepth = false;

// Debuggin
var originalEmit = myCrawler.emit;
myCrawler.emit = function(evt, q) {
    console.log(evt, q && q.url || "No URL");
    originalEmit.apply(myCrawler, arguments);
}

myCrawler.on("fetchstart", function(queueItem, requestOptions) {
  console.log(queueItem.url);
});

myCrawler.on("fetchcomplete", function(queueItem, data, response) {
    console.log("%s (%d bytes)", queueItem.url, data.length);
    console.log("It was a resource of type %s", response.headers['content-type']);

    if(response.headers['content-type'].indexOf('text/html') >= 0) {
      links.push(queueItem.url);
    }
});

myCrawler.addFetchCondition (function (url) {
    return ! url.path.match( /\.png|\.css|\.jpeg|\.js|\.jpg|\.ico|\.gif|\.zip/i );
});

myCrawler.on("complete", function() {
  console.log(links);
});

myCrawler.start();
``

**Comment by cgiffard** [comment]
It would be an understatement to say that the tests around that feature are lacking — I think I'll try to fire up a good set of test cases before I work out what might be wrong.

Can you confirm that you're having the issue when crawling `cssmenumaker.com`?

**Comment by rolfen** [comment]
I've had the same issue despite 
crawler.fetchWhitelistedMimeTypesBelowMaxDepth == false
This is how I've gotten around it:

    // wrap default discovery function with a depth check
    var defaultCrawlerResourceDiscoveryFunction = crawler.discoverResources;
    crawler.discoverResources = function(buf, queueItem) {
        if(queueItem.depth < input.depth) {
            var ret = defaultCrawlerResourceDiscoveryFunction.call(crawler, buf, queueItem);
        } else {
            debugLog("Max level reached, inhibiting further discovery.")
            var ret = [];
        }
        return ret;
    };
