### ISSUE TITLE
ajaxed contet pages crawl problem

### ISSUE THREAD

**Issue by Placebo** [cgiffard/node-simplecrawler#159]
Hi

i have a huge issue that make this script and any other worthless for me

im using this script for crawling some shopping sites

we are planing to crawl a page a shopping website called digikala (www.digikala.com)

the problem is the main product grids load their data from an ajax call

for example this page : http://www.digikala.com/Search/Category-Mobile-Phone/#!/Brand-10/Category-Electronic-Devices/Category-Mobile/Category-Mobile-Phone/

If you see your firebug/developer-console u will see that the products grid of this category is loading after an ajax post call

so how can i crawl this product pages

add some wait (for example 10 sec) before fetch the page will fix the issue?

plz help

**Comment by BrandonCouts** [comment]
So you seem to have a fundamental error understanding how the the crawler works. It only grabs the string of an html page, (hence the simple part of 'simple-crawler') and searches via regex for urls on the page. In order for the crawler to index these ajax calls, __urls need to be found__. There are two ways you can handle this:

* You figure out how if they hard coded the ajax urls in the product page, and rewrite the crawlers discoveryRegex to discover their request pattern.
* Or you can 'guess' the ajax call when you discover the page, and add the ajax url manually to crawlers the fetch list. (In your script not the crawlers)

If you NEED to have javascript/ajax support natively, this is not the crawler for you. You need a headless browser like zombie.js, or Phantom.js. Simple crawler is just what it says, simple. Its best use case is for fetching sites which render on the server, and uses javascript minimally.

Best of luck.

PS: Its worth noting if this is your site, that google may not be crawling it, as it doesn't seem to conform:
https://developers.google.com/webmasters/ajax-crawling/docs/learn-more
https://developers.google.com/webmasters/ajax-crawling/docs/specification?hl=en

**Comment by cgiffard** [comment]
It is possible to use SimpleCrawler for this, but will not catch arbitrary AJAX.

It's my recommendation that you write a custom discovery function which calls and understands the results from the AJAX calls, and appends those to the queue. You can see a rough example of this in the documentation:

> **crawler.discoverResources** - Use simplecrawler's internal resource discovery function. You can replace it with your own function, which must accept a buffer and a queueItem, and add the discovered resources to the crawler queue:

> ```js
crawler.discoverResources = function(buf, queueItem) {
    // scan buffer for URLs, and then:
    ...
    crawler.queueURL(aDiscoveredURL, queueItem);
    ...
};
> ```
