### ISSUE TITLE
parseScriptTags not working properly

### ISSUE THREAD

**Issue by lgraubner** [cgiffard/node-simplecrawler#165]
If the option `parseScriptTags` is set to false simplecrawler only crawls the first page and stops. I recognized this behavior with the Content Management System [Contao](https://contao.org/de/). It can be tested with the [demo](http://demo.contao.org/en/). Probably it is not a problem with Contao only, I couldn't figure out the problem yet. Maybe some different HTML Markup.

**Comment by lgraubner** [comment]
A little addition:

The reason I disabled this option was the following problem:

```JavaScript
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
```

Simplecrawler detects `g;m.parentNode.insertBefore(a,m)` as URL. But this is obviously wrong. The snippet is the default Google Analytics snippet, placed right before the closing `body` tag.

**Comment by lgraubner** [comment]
The Problem is this regex in `crawler.js` line 152:

```JavaScript
/\s?(?:href|src)\s?=\s?[^"'][^\s>]+/ig
```

In which case there is a href/src without any quotes?

Sorry for spamming this issue.

**Comment by cgiffard** [comment]
That's OK — good catch. One of the things SimpleCrawler tries to do with the *default* discovery mechanism (easily replaceable with something much more sophisticated) is to detect every URL possible, even if false positives are returned (each URL then goes through a process of cleanup, hopefully removing most of the really mangled ones.)

The bug in my mind, therefore, isn't that the URL is discovered — although more tuning could perhaps be done — but that the crawler stops crawling. Is it locked up on that URL? Or perhaps all the other pages are on a different domain/subdomain? What does the queue look when it stops?

**Comment by lgraubner** [comment]
I found the problem. The regex to replace all script tags if `parseScriptTags` is set to `false` assumes on or more characters inside the tags. But if you use `src` this is most likely empty and will remove a lot more source code. I provided pull request which fixes this problem.

Regarding my second comment I will look into the URL discovery, thanks for your help.
