### ISSUE TITLE
Add Contributor Guidelines

### ISSUE THREAD

**Issue by cgiffard** [cgiffard/node-simplecrawler#169]
These are sorely lacking.

A few things need to be detailed:

* Advice for filing PRs
* Commit standards
* Linting/testing standards
* Advice on philosophy — i.e. what features are intended to be in simplecrawler core and which ones really aren't

**Comment by fredrikekelund** [comment]
Nag nag, @cgiffard  :wink: You think part of this can be addressed by adding [issue and PR templates](https://github.com/blog/2111-issue-and-pull-request-templates)?

**Comment by cgiffard** [comment]
I think we could add part of it like that, and the other part should be a nice, clear CONTRIBUTING.md with a link from the readme. :)

**Comment by cgiffard** [comment]
@fredrikekelund I've added some guidelines as a basic first cut — don't hesitate to let me know if you think they're overbearing or need adjustment!

I thought about adding a code of conduct, but didn't really want to get all didactic on people (well, any more than I already was!) It's still bouncing around the back of my mind though.
