### ISSUE TITLE
Ensure URI #fragments are stripped from URIs, and test for this

### ISSUE THREAD

**Issue by cgiffard** [cgiffard/node-simplecrawler#179]
At present, it appears URI fragments are being sent to the server, when they should be known only to the client. We should strip them out.

**Comment by fredrikekelund** [comment]
@cgiffard I added a test in https://github.com/cgiffard/node-simplecrawler/commit/ca9bef627f3d5359a415068fb99284997f2945b2, and it seems fragment identifiers are being stripped already.

**Comment by cgiffard** [comment]
Cool. I'll close this issue! :)
