### ISSUE TITLE
WP /feed/ url not being crawled

### ISSUE THREAD

**Issue by asmerkin** [cgiffard/node-simplecrawler#180]
Hello, 

I'm crawling a Wordpress Install. Everything is fine until the crawler reaches the /feed/ url and it gets stucked there. 

It has a hard time scanning http://centricdigital.com/contact/feed/

What can this be?

**Comment by fredrikekelund** [comment]
Hmm, does the crawler simply get stuck or does it throw an error?

**Comment by asmerkin** [comment]
It just gets stuck at that point.



Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=7.4.10&pv=5.0&source=email_footer_2] On lun., nov. 02, 2015 at 6:05 AM, Fredrik Ekelund < notifications@github.com [notifications@github.com] > wrote:
Hmm, does the crawler simply get stuck or does it throw an error?

—
Reply to this email directly or view it on GitHub
[https://github.com/cgiffard/node-simplecrawler/issues/180#issuecomment-152962296] .[https://github.com/notifications/beacon/AAd0ocz0lGW_pbLQQeJwwflMkWY-o7sKks5pBx7jgaJpZM4GWlEy.gif]

**Comment by fredrikekelund** [comment]
I tried to reproduce your problem with simplecrawler 0.5.4 and the following script, but it seems the crawler passed http://centricdigital.com/contact/feed/ without any issues.

What version of simplecrawler do you use? Do you use a custom discoverResources function or any other custom configurations?

```js
var Crawler = require("simplecrawler");

var crawler = new Crawler("centricdigital.com");
crawler.maxConcurrency = 5;
crawler.timeout = 60 * 1000;

var log = function () {
	lastRunMsAgo = 0;

	var time = /(\d+:\d+:\d+)/.exec(new Date().toString())[1];
	Array.prototype.unshift.call(arguments, time);
	console.log.apply(console, arguments);
};

var freezeAfter = 5 * 60 * 1000,
	lastRunMsAgo = 0;

var stopScraperInterval = setInterval(function () {
	lastRunMsAgo += 100;

	if (lastRunMsAgo >= freezeAfter) {
		clearInterval(stopScraperInterval);
		log("Stopping crawler because of timeout after", freezeAfter / 1000, "seconds");
		process.exit();
	}
}, 100);

crawler
	.on("fetchcomplete", function (queueItem, responseBuffer, response) {
		log("Done:", queueItem.url);
	})
	.on("fetch404", function (queueItem, responseBuffer) {
		log("404:", queueItem.url);
	})
	.on("fetcherror", function (queueItem, responseBuffer) {
		log("Error:", queueItem.url);
	})
	.on("fetchtimeout", function (queueItem, timeoutVal) {
		log("Timeout:", queueItem.url);
	})
	.on("fetchredirect", function (queueItem, parsedUrl) {
		log("Redirect", queueItem.url);
	})
	.on("complete", function () {
		clearInterval(stopScraperInterval);
		console.timeEnd("Crawl");
		log("Finished scraping!");
	});

console.time("Crawl");
crawler.start();
```

**Comment by asmerkin** [comment]
Yes, you're right.

It must have been a connectivity issue. Now it's working fine. Maybe the
feed was very long.

Thank you!

2015-11-03 9:05 GMT-03:00 Fredrik Ekelund <notifications@github.com>:

> I tried to reproduce your problem with simplecrawler 0.5.4 and the
> following script, but it seems the crawler passed
> http://centricdigital.com/contact/feed/ without any issues.
>
> What version of simplecrawler do you use? Do you use a custom
> discoverResources function or any other custom configurations?
>
> var Crawler = require("simplecrawler");
> var crawler = new Crawler("centricdigital.com");
> crawler.maxConcurrency = 5;
> crawler.timeout = 60 * 1000;
> var log = function () {
>     lastRunMsAgo = 0;
>
>     var time = /(\d+:\d+:\d+)/.exec(new Date().toString())[1];
>     Array.prototype.unshift.call(arguments, time);
>     console.log.apply(console, arguments);
> };
> var freezeAfter = 5 * 60 * 1000,
>     lastRunMsAgo = 0;
> var stopScraperInterval = setInterval(function () {
>     lastRunMsAgo += 100;
>
>     if (lastRunMsAgo >= freezeAfter) {
>         clearInterval(stopScraperInterval);
>         log("Stopping crawler because of timeout after", freezeAfter / 1000, "seconds");
>         process.exit();
>     }
> }, 100);
>
> crawler
>     .on("fetchcomplete", function (queueItem, responseBuffer, response) {
>         log("Done:", queueItem.url);
>     })
>     .on("fetch404", function (queueItem, responseBuffer) {
>         log("404:", queueItem.url);
>     })
>     .on("fetcherror", function (queueItem, responseBuffer) {
>         log("Error:", queueItem.url);
>     })
>     .on("fetchtimeout", function (queueItem, timeoutVal) {
>         log("Timeout:", queueItem.url);
>     })
>     .on("fetchredirect", function (queueItem, parsedUrl) {
>         log("Redirect", queueItem.url);
>     })
>     .on("complete", function () {
>         clearInterval(stopScraperInterval);
>         console.timeEnd("Crawl");
>         log("Finished scraping!");
>     });
> console.time("Crawl");
> crawler.start();
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgiffard/node-simplecrawler/issues/180#issuecomment-153333535>
> .
>



-- 
Andrés Smerkin
http://www.andressmerkin.com.ar

**Comment by fredrikekelund** [comment]
Alright, good to hear!
