### ISSUE TITLE
utf8 support

### ISSUE THREAD

**Issue by tomtom87** [cgiffard/node-simplecrawler#182]
Hi,

I have been loving using your crawler. One of the best solutions I have found yet. All is well just I happen to be __that user__ that found the `TODO` note in `Crawler.js` and I have been trying for the past day or so to get 'er working. To no avail.

I am currently trying the following things:

1. Conversion with Iconv from the Byte string inside `discoverResources` method:
```js
var iconv = new Iconv(encoding["encoding"], 'UTF-8');
var resourceData = iconv.convert(resourceData);
```

This results in a error from iconv

```lib/iconv.js:141
<         throw errnoException('EILSEQ', 'Illegal character sequence.');
<         ^
< Error: Illegal character sequence.
```

I know the byte data is ok because I am checking it with the following:

```
console.log(util.inspect(resourceData));
console.log(jschardet.detect(resourceData));
< <Buffer 3c 21 44 4f 43 54 59 50 45 20 68 74 6d 6c 20 50 55 42 4c 49 43 20 22 2d 2f 2f 57 33 43 2f 2f 44 54 44 20 58 48 54 4d 4c 20 31 2e 30 20 54 72 61 6e 73 ... >
< { encoding: 'TIS-620', confidence: 0.7218912566898091 }
```

2. Setting encoding on the HTTP request
```js
// Get the resource!
        clientRequest =
            client.request(requestOptions, function(response) {
                response.setEncoding('utf8');
                crawler.handleResponse(queueItem, response, timeCommenced);
            });
```

This results in breaking with the error `TypeError: chunk.copy is not a function` from this line
```js
} else {
                // Copy the chunk data into our main buffer
                chunk.copy(responseBuffer, responseLengthReceived, 0, chunk.length);
            }
```

I'm not sure why because in the REPL I can view the data of responseBuffer, but once adding the setEncoding sure as hell .copy is not set.

I would love to implement this feature and will continue trying, if you have any suggestions on why or how to get iconv properly converting the string that would be great.Thanks!

**Comment by tomtom87** [comment]
btw this is from scraping a Thai character set website. As far as I know I can store the characters into UTF-8. I used to do this in PHP with iconv, so hope the same will apply here - unless there is some caveats I am unaware too. Didn't reach any conclusion from documentation so far.

**Comment by fredrikekelund** [comment]
If I understand your problem correctly, you want to decode the contents of the page before discovering resources? I'm thinking that URL's should generally be URL encoded, so I'm not sure how much effect this would have. But in any case, here's how I would go about it.

I would reuse the `discoverResources` method from here https://github.com/cgiffard/node-simplecrawler/issues/130#issuecomment-103065621. Then I would monkey patch the discoverResources method like this:
```js
var originalDiscoverResources = myScraper.discoverResources.bind(myScraper);

myScraper.discoverResources = function (responseBuffer, queueItem) {
	var decodedBody = decodeResponse(responseBuffer, response.headers["content-type"]);

	return originalDiscoverResources(decodedBody, queueItem);
};
```

Let me know if this helps your problem!

**Comment by tomtom87** [comment]
@fredrikekelund  actually no, crossed wires here - that part works fine and the URLs are getting encoded to html entities the actual problem lies in getting the response buffer data, in crawler.js there is a todo note to add UTF8 support. I wish to add that support.

**Comment by fredrikekelund** [comment]
My bad, that should've been clear to me from your original post, really.

Just to make sure we're on the same page, though - UTF-8 support is there right now, it's other text encodings that aren't accounted for (ie. no effort is made to detect the encoding of the response body). 

I know I've run into this problem when working with simplecrawler, but this has been discussed before in #45 and the decision then was to avoid implementing it at the simplecrawler level. But if we were to use `iconv-lite` (which has no native bindings) over `iconv` I would probably be in favor of implementing this, seems like a way to save effort on the developer's part. What do you think @cgiffard?

I actually have some code I'm using to do this on my own right now, I could make a PR from that and see if this helps the problems you were having.

**Comment by tomtom87** [comment]
@fredrikekelund  no worries, well I'm confused because I cannot get UTF8 working at all. going to try with @cgiffard said on #45 

It is this [line here](https://github.com/cgiffard/node-simplecrawler/blob/master/lib/crawler.js#L531) I am wondering about:

```
Crawler.prototype.discoverResources = function(resourceData, queueItem) {
    // Convert to UTF-8
    // TODO: account for text-encoding.
    var resourceText = resourceData.toString("utf8"),
        crawler = this;
```

Will let you know how I get on with the toString('uft8') and iconv-lite idea.

**Comment by cgiffard** [comment]
Hey! Sorry about my slowness in helping out with these issues. :(

I noted that there because I was looking to handle a couple of edge cases I'd seen in EUC-JP where URLs were not properly encoded — but, for the most part, URIs are only ever 7 bit ASCII, which is common to most encodings. So I decided to avoid (for now) the cost of the conversion every time, and instead just assume the input is UTF-8.

**Comment by cgiffard** [comment]
Are you having problems in link discovery as a result of the Thai character set specifically? Or would you like to provide UTF-8 text as a convenience via the API?

**Comment by tomtom87** [comment]
@cgiffard Thanks for getting back to me man :) The problem is the actual webpage data is coming out with these ???? characters and I cannot get the actual content..

**Comment by cgiffard** [comment]
Are the links being discovered? Is any of the data readable at all? Or is everything completely mangled? (As in, you can't make any sense of page structure regardless of whether the text is readable.)

**Comment by tomtom87** [comment]
@cgiffard Yes the links are fine because the characters are becoming url encoded html entities, it is just the actual page contents that gets mangled and only the thai characters all english characters are fine and the html markup is fine also. Thanks for getting back to me

**Comment by fredrikekelund** [comment]
@tomtom87 would it be possible for you to share what page it is you're working with? Might be helpful to see what headers are sent etc

**Comment by tomtom87** [comment]
@fredrikekelund sure thing it's just here http://www.haru-harashop.com/shop-haruhara-module-product-new-page1.html

The page is being detected as `{ encoding: 'TIS-620', confidence: 0.7239134250549037 }` with `jschardet` npm module

The urls come in as so `http://www.haru-harashop.com/haruhara-item-JOA-Cream-Pack-%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%CB%B9%EF%BF%BD%D2%A2%EF%BF%BD%EF%BF%BD-%EF%BF%BD%EF%BF%BD-%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD-%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD-%28%EF%BF%BD%EF%BF%BD-%EF%BF%BD%EF%BF%BD-%EF%BF%BD%EF%BF%BD%EF%BF%BD-%EF%BF%BD%CD%A7%EF%BF%BD%EF%BF%BD%EF%BF%BD-10-pid761826.html`

But the page content is as so

```
���Slim Express ���� ��硫����� �������෾ �ٵù����Ҩҡ�������� \', `post_author` = \'4\', `post_content` = \'\\n          Slim Express ���� ��硫����� �������෾ �ٵù����Ҩҡ��������         ,\\n        Slim Express ���� ��硫����� �������෾ �ٵù����Ҩҡ�������� ἧ�� 120.-/ 5 ἧ��� 110 / 10 ἧ��� 100.-\\n \\n���������觡����Ҿ�ҭ���ѹ��ǹ��Թ������ǡ��� �ѡ�Ѻ ���ѹ ���� ��ӵ�� Ŵ������ҡ����� �����к��Ѻ���� ����բ��� ������� Ŵ��ԧ �ش��������ʡѴ�ҡ�����ҵ� ��ҡ���ª�Դ ������ѹ���� ����Ţ�ҧ���§ ����֡����֧��������¹��ç����� 1 ����\\n \\n��ǹ��Сͺ�Ӥѭ\\n \\n���ʡѴ�ҡ���Ǣ�� \\n�Ѻ���� ��ſ�-������ �ҡ�Ѻ��͹ ��з�˹�ҷ�������¹������繹�ӵ�š����ʡ�͹����дٴ������������ҧ��� �������ҧ�������Ѻ��ѧ�ҹ�ҡ��駹���ŧ Ŵ������ҡ������������֡�����ҹ���� \\n \\n����кͧྪ� \\n��Сͺ������÷�����ķ�������¹�ӵ�š����� ���������������� ����Ŵ������ҡ����� ������������֡��� ������ø����ҵ����§��Դ����Ƿ���ѡ�Է����ʵ���׹�ѹ����������Ŵ�������(appetite suppressant) ����֧ 40-60% �ѧ����������� (dietary fiber) �������ö�Ѻ�Ѻ���ѹ (fat binder) ������ա���� ����ѧ�����������ѹ���� \\n 
```

**Comment by tomtom87** [comment]
FYI when I try a iconv conversion I get the following error:

```
simplecrawler/node_modules/iconv/lib/iconv.js:141
        throw errnoException('EILSEQ', 'Illegal character sequence.');
```

**Comment by fredrikekelund** [comment]
I used `iconv-lite` to decode the response buffer based on the encoding specified in the Content-Type header and got [this result](http://pastebin.com/0fYWv8Qq). Does that look correct?

Here's the code I used (the `decodeResponse` method is copy-pasted from my own project):

```js
var Crawler = require("simplecrawler"),
	iconv = require("iconv-lite");



var crawler = new Crawler("www.haru-harashop.com", "/shop-haruhara-module-product-new-page1.html");
crawler.maxConcurrency = 5;
crawler.timeout = 60 * 1000;



var decodeResponse = function (buffer, contentTypeHeader) {
	contentTypeHeader = contentTypeHeader || "";

	var embeddedEncoding = /<meta.*charset=(?:"|'){0,1}([^"|']*)[^>]/i.exec(buffer.toString(undefined, 0, 512)) || [],
		encoding = contentTypeHeader.split("charset=")[1] || embeddedEncoding[1] || contentTypeHeader;

	encoding = iconv.encodingExists(encoding) ? encoding : "utf-8";

	return iconv.decode(buffer, encoding);
};



crawler.on("fetchcomplete", function (queueItem, responseBuffer, response) {
	console.log("Done:", queueItem.url);

	var body = decodeResponse(responseBuffer, response.headers["content-type"]);
	console.log(body);

	crawler.stop();
});

crawler.start();
```

It seems they specify the same charset in the Content-Type header as was detected in your code (tis-620). So as long as the result I linked above is correctly interpreted, this looks like a problem with the iconv module?

But once again, I'd probably be in favor of adding a method like the one above to simplecrawler's core. Maybe behind a `forceUTF8`-like flag.

**Comment by tomtom87** [comment]
@fredrikekelund genius! yes that is the correct decoding! Thank you so so much!! I will try with your code and see what it is. 

If this was in the core I think simplecrawler is by far one of the best crawlers available

**Comment by fredrikekelund** [comment]
Glad to hear it helped you out :) I'll go ahead and open a PR for this, and we can continue the discussion there around whether or not to implement this in.

@tomtom87 maybe you can close the ticket once you've confirmed whether or not this worked for you?

**Comment by tomtom87** [comment]
@fredrikekelund  it's working!! So happy right now I owe you man! This is great :) Thanks for really giving me a great weekend :100:

**Comment by fredrikekelund** [comment]
Haha no worries! :cocktail: Keep an eye out in #183 to see when this makes it into core
