### ISSUE TITLE
Crawler event on depth change

### ISSUE THREAD

**Issue by rolfen** [cgiffard/node-simplecrawler#187]
This is a feature request.
I suggest having a "newlevel" event fired when the crawler depth changes or when all resources for a level/depth have finished processing.

**Comment by fredrikekelund** [comment]
Sorry about the very tardy response on this one! My only concern is how this works if resources are queued manually - is it a problem if the queue depth "starts over"? Or maybe we shouldn't be concerned about that, since it's just a natural consequence of how the crawler works

**Comment by cgiffard** [comment]
The crawler could be crawling any number of depths concurrently — there isn't a single depth level. I'm not sure what the utility of this would be.

**Comment by fredrikekelund** [comment]
@rolfen do you have an example of when this could be useful as opposed to just reading the depth in `fetchcomplete`?

**Comment by cgiffard** [comment]
Closing for now, as I think this can be served in other ways.
