### ISSUE TITLE
The call backs

### ISSUE THREAD

**Issue by bfwg** [cgiffard/node-simplecrawler#195]
I'm looking through the code and I see almost all the functions have a callback function in their params even the function is not a async function. I'm new to Javascript but doing something like this in queue.js
```js
FetchQueue.prototype.exists = function(protocol, domain, port, path, callback) {
    callback = callback && callback instanceof Function ? callback : function() {};

    port = port !== 80 ? ":" + port : "";

    var url = (protocol + "://" + domain + port + path).toLowerCase();

    if (this.scanIndex[url]) {
        callback(null, 1);
        return 1;
    }

    this.scanIndex[url] = true;
    callback(null, 0);
    return 0;

};
```
Is it the same as doing something like this
```js
FetchQueue.prototype.exists = function(protocol, domain, port, path) {

    port = port !== 80 ? ":" + port : "";

    var url = (protocol + "://" + domain + port + path).toLowerCase();

    if (this.scanIndex[url]) {
        return 1;
    }

    this.scanIndex[url] = true;
    return 0;

};

```

**Comment by cgiffard** [comment]
They are roughly equivalent. However, while the default FetchQueue in SimpleCrawler is synchronous, the intention is that it implements an async API, to allow async queues. Think, a queue backed by Redis, or Mongo, etc.

**Comment by cgiffard** [comment]
The value is returned from the function to maintain compatibility with older code, back when the FetchQueue interface was synchronous only, and did not take callbacks.

**Comment by bfwg** [comment]
I understand now, thank you!
