### ISSUE TITLE
Complete crawl after X resources completed

### ISSUE THREAD

**Issue by namklabs** [cgiffard/node-simplecrawler#199]
The .stop() method doesn't emit the complete event, but I want to stop my crawler after X many fetchcomplete events and still emit the complete event. Is there a way to do this?

**Comment by fredrikekelund** [comment]
Sure, just use the standard EventEmitter methods (simplecrawler inherits from EventEmitter)! The `complete` event doesn't supply any arguments, so all you need to do is to keep a counter of the number of fetched pages, check that counter for every `fetchcomplete` event and then do something like:

```js
if (myCounter === fetchLimit) {
	myCrawler.stop();
	myCrawler.emit("complete");
}
```
