### ISSUE TITLE
handle many initial URLs

### ISSUE THREAD

**Issue by benoitpointet** [cgiffard/node-simplecrawler#204]
I'd like to use simplecrawler to check some properties of sets of websites (10 to 100). I played a bit with it but am having a bit of troubles with the concepts of initial URL and adding things to the queue in simplecrawler.

What's the best way to crawl with many start-URLs?

**Comment by fredrikekelund** [comment]
I would probably just create one instance of simplecrawler for each site. Running 10-100 instances in parallell sounds a bit intense, though, so try limiting the number of parallell crawler instances. As for adding new URL's, see that [section in the README](https://github.com/cgiffard/node-simplecrawler#adding-to-the-queue)
