### ISSUE TITLE
ignoring initialPath

### ISSUE THREAD

**Issue by hristod** [cgiffard/node-simplecrawler#207]
When I set the property as, for example:
    myCrawler.initialPath = '/en'
the crawler still starts from the root URL (www.example.com instead of www.example.com/en/).

**Comment by cgiffard** [comment]
Can you paste a code example which exhibits this problem?

**Comment by hristod** [comment]
Sure, here is an example (It've cut out much of my code, since it doesn't concern the example. I hope I didn't mess up :)

      // Exclude anything except for links
      var exclude = ['gif', 'jpg', 'jpeg', 'png', 'ico', 'bmp', 'ogg', 'webp',
        'mp4', 'webm', 'mp3', 'ttf', 'woff', 'json', 'rss', 'atom', 'gz', 'zip',
        'rar', '7z', 'css', 'js', 'gzip', 'exe'];
      var exts = exclude.join('|');
      var regexReject = new RegExp('\.(' + exts + ')', 'i');

      // Crawler configuration
      var crawler = new Crawler('www.clinicafertia.com');
      crawler.initialPort = 80;
      crawler.initalPath = '/en/fertility/';
      crawler.maxConcurrency = 10;
      crawler.ignoreWWWDomain = false;

      crawler.addFetchCondition(function (parsedURL) {
        return !parsedURL.path.match(regexReject);
      });


      // Run the crawler
      crawler.start();

      crawler.on('fetchcomplete', function(item, responseBuffer, response) {
        console.log('Scanning: ', item.url);
      });

      // Completed crawling. Now let's get to work!
      crawler.on('complete', function() {
        console.log('Crawl complete!')
      });

**Comment by fredrikekelund** [comment]
It looks like you've misspelled it - `initalPath` should be `initialPath` :)

**Comment by hristod** [comment]
Seriously, I am an idiot :D Thanks for the help!
Cheers!

**Comment by fredrikekelund** [comment]
No worries!
