### ISSUE TITLE
"fetcherror" event w/ HTTP 200 (OK) status code

### ISSUE THREAD

**Issue by tibetty** [cgiffard/node-simplecrawler#213]
```js
const webSite = 'www.jnto.go.jp';
const protocol = 'http';
const port = 80;
const initialPath = '/eng';

var crawler = new Crawler(webSite);
crawler.initialProtocol = protocol;
crawler.initialPort = port;
crawler.initialPath = initialPath;
crawler.maxDepth = 3;

crawler
.on('crawlstart', function() {
})
.on('fetchcomplete', function(queueItem, responseBuffer, response) {
    console.log('Received %s (%d bytes)', queueItem.url, responseBuffer.length);
})
.on('fetcherror', function(queueItem, response) {
	console.log('Error #%d (%s) happened when retrieve %s', response.statusCode, response.statusMessage, queueItem.url);
})
.start();
```
When I use simplecrawler to crawl "http://www.jnto.go.jp/eng/", I met a strange error:
Error #200 (OK) happened when retrieve http://www.jnto.go.jp/eng/pdf/regional/tohoku/fukushima.pdf

'Coz the requested resource is a 16M+ pdf file, I suppose it's a severe internal error, e.g., exceeding the upper boundary of buffer, etc., and the worst thing is that the crawler itself pend crawling since then.

Any contributors wants to look inside and have it fixed in future release?

**Comment by fredrikekelund** [comment]
Ah yes, you're right - it's supposed to be a `fetchdataerror` event, but I see now that that's only emitted if the initial Content-Length header is smaller than maxResourceSize. Otherwise, a `fetcherror` event is emitted. I'll take a look at fixing it, thanks for reporting!

**Comment by fredrikekelund** [comment]
I've fixed the issue, please give the latest master a try if you depend on the correct behavior!

**Comment by tibetty** [comment]
:+1: Thanks for your prompt action, @fredrikekelund !  I believe the issue has been correctly addressed from the changes you made to the new source, however, the website prevents me from reproducing the exactly same behavior maybe because their webmaster found out and blocked my "attacking" attempts, :)

**Comment by cgiffard** [comment]
Update the userAgent flag and try from a different IP address. Of course, if people are blocking you, it might be that you're flogging the destination website too hard. Consider backing off a little.

**Comment by tibetty** [comment]
Thank @cgiffard for the advice!  I reran my workload, and encountered a severe issue, will report it out in a separate thread.
