### ISSUE TITLE
Publish new version to registry

### ISSUE THREAD

**Issue by tmpfs** [cgiffard/node-simplecrawler#218]
Thanks for this project, absolutely awesome.

I was trying to work out why my fetch condition was not getting a second argument and finally worked out that the docs are out of sync with the npm package (I get the second argument with the latest version in git). Can you cut and publish a new version please?

I prefer to avoid git based dependencies wherever possible ;)

**Comment by cgiffard** [comment]
This feature only landed a few hours ago — we'll tidy a couple of things up and push one shortly. Sorry for the inconvenience! :)

**Comment by tmpfs** [comment]
No worries - thanks for being so prompt! :)

**Comment by tmpfs** [comment]
FYI, I just worked out how to deploy from travis on tagged commit, need to encrypt your npm API key in the travis config, but it's a real time saver, my config is here:

https://github.com/tmpfs/linkdown/blob/master/.travis.yml

Works like a charm! No more `npm pub` for me :)

**Comment by fredrikekelund** [comment]
Looks like @cgiffard published a version 0.6.2 with the changes to fetch conditions included :)

**Comment by tmpfs** [comment]
Great! I've updated and everything working as expected - thanks!

**Comment by cgiffard** [comment]
@fredrikekelund I haven't made a release yet though — doing that now. :)
