### ISSUE TITLE
Question on status code 599

### ISSUE THREAD

**Issue by tmpfs** [cgiffard/node-simplecrawler#219]
I was trying to work out why nothing printed when my service was down and I finally got it by listening for the `fetchdataerror` event, however when an `ECONNREFUSED` error is handled I wonder whether `503 Service Unavailable` would be more appropriate rather than the non-standard 599 status code.

**Comment by tmpfs** [comment]
Happy to submit a pull request for this, if you agree.

**Comment by cgiffard** [comment]
In this instance, 599 is deliberately nonstandard — we've experienced an error internally to the *client*, and we want to make sure it's distinct from a server response.

If we were a proxy communicating via HTTP, I'd agree that 503 would be more appropriate, as we'd be signalling that we received an upstream connection error. But in this case I feel like the error should be distinct (unless you've got a compelling rationale to the contrary!) :)

**Comment by cgiffard** [comment]
That said, it's funny that you got a `fetchdataerror` and not a `fetcherror` in this case. Are you able to put together a small test case demonstrating the problem?

**Comment by tmpfs** [comment]
I may be wrong about which error event it was, there are a few ;) I'll check.

**Comment by tmpfs** [comment]
I understand your point of view, but from the wikipedia page on status codes it is not implied that 503 is only for downstream proxy services:

> The server is currently unavailable (because it is overloaded or down for maintenance). Generally, this is a temporary state.

However I see how you would want to distinguish this error from others. I can easily switch 599 to 503 in my code anyhow, or maybe we should treat this as a completely separate error event for the implementation to handle?

**Comment by tmpfs** [comment]
Sorry my bad, it was actually `fetchclienterror` which I believe is correct semantically.

**Comment by cgiffard** [comment]
In this case, `fetchclienterror` always indicates that there was an error making the request, so you can safely handle the 599s in isolation using this event. If you scan the queue independent of the event, you can use the `599` to be able to determine that a particular queue item failed at the client rather than at the server.

Perhaps the 5XX series of errors is not the place to put this, since it's a client error, not a server error. We could change it to 499, or maybe invent a new 6XX error code, for instance.

**Comment by tmpfs** [comment]
Hmm, I'm not totally sure about that. If the server is down how is it a client error? Sure it's a *client request* error but the fault lies with the server.

Personally I would be really keen to stick with the existing standard HTTP response codes that people are familiar with ;)

**Comment by cgiffard** [comment]
Well I think it's important that it's clear from the status code that the error wasn't delivered via HTTP from the destination. If we used 503, say, while it might be semantically correct, we wouldn't be able to determine whether the server returned the 503 or whether we invented it because we couldn't get upstream (even if it's the server's fault.)

I'm inclined to use a non-standard code *purely because* it won't be confused with anything a server might return.

**Comment by tmpfs** [comment]
I see that point of view too, your call of course ;)

**Comment by tmpfs** [comment]
> maybe invent a new 6XX error code

Out of all the options so far and given your feeling for a non-standard code for this scenario, I think maybe the above is the best option: `600`.

I actually checked if `599` was a valid status code just to be sure before I raised this, if people see 600 for sure they know something is up!

**Comment by fredrikekelund** [comment]
I like your reasoning around the error code, @cgiffard, I agree it would be more confusing if we swapped it out for 503 (or any other valid status code).

But I don't have any objections to changing the status code to 600, it might make things clearer. It's easier to filter based on `status` anyway, so it probably isn't that big of a deal if we were to change the status code

**Comment by fredrikekelund** [comment]
@cgiffard decision on this one?

**Comment by cgiffard** [comment]
@fredrikekelund Let's go with 600, and make sure it's in the docs. I'm happy to do that if you're busy!

**Comment by cgiffard** [comment]
@fredrikekelund Thinking we should probably start assigning issues so we don't double up, haha.

**Comment by fredrikekelund** [comment]
@cgiffard cool! Yeah, good idea - I'll leave this one to you then :)

**Comment by cgiffard** [comment]
Nice! I'll fix it now. :)

**Comment by cgiffard** [comment]
Fixed in 88f8a08907446bde8584730d5a1105a6dbc18d35.

Queued up for an 0.8 release when ready!

**Comment by tmpfs** [comment]
Thanks for keeping the momentum going folks, I just upgraded to `0.7.0` without a hitch and will check this out when `0.8.0` is released.

**Comment by cgiffard** [comment]
Hah, it's mostly @fredrikekelund doing all the work! (I've blocked out today to try and catch up myself, haha.)

I've closed this issue because the code has been merged, and unless something horrendously untoward happens, it'll be released soon!
