### ISSUE TITLE
Different events for 404 and 410 

### ISSUE THREAD

**Issue by tmpfs** [cgiffard/node-simplecrawler#220]
I think the event name ambiguity is a little misleading (although it is documented in the readme that 410 triggers `fetch404`). I have implemented a quick fix for this to distinguish the event names if you want the pull request?

My rationale is that `fetch404` should not have the `410` event status code bundled in because there are instances when they would need to be handled differently.

My use case is that I am building a tool that downloads all `text/html` and `application/xhtml+xml` pages and validates them using the [nu validator](https://github.com/validator/validator). I want to add the logic to download and validate 404 errors but ignore 410 errors. Clearly I can just switch on the status code in `fetch404` but there is something about the event name that bothers me.

I suggest that either:

* `fetch404` and `fetch410` are emitted (quickly implemented, tests passing)
* the event name is renamed to `notFound` or something similar

Sorry if this is a little pedantic.

**Comment by tmpfs** [comment]
Clearly, renaming to `notFound` is a breaking change and requires a minor version bump, as does distinguishing event names too (people might already be switching on status code in `fetch404`).

**Comment by cgiffard** [comment]
Good suggestion, and definitely an artefact of simplecrawler's evolution. I'm thinking we could add a `notFound` event which would take both 404s and 410s, but remove the 410 responses from emitting a `fetch404`, which is clearly confusing.

**Comment by tmpfs** [comment]
I was thinking it wouldn't hurt to emit `notFound`, `fetch404` and for consistency also emit `fetch410`. That should cover all requirements. I don't think emitting the additional events would impact performance much, this should do the trick:

```javascript
// Emit 404 event
crawler.emit("fetch" + response.statusCode, queueItem, response);
crawler.emit('notFound', queueItem, response);
```

**Comment by fredrikekelund** [comment]
I think separating the 404's and the 410's sounds like a sound idea! I'm not 100% sure that making 3 events out of 1 feels like the best way to go about this though (but I'm not 100% sure it's the wrong way either). Instinctively I'd probably vote for doing one `fetchnotfound` (404 and 410) and one `fetch404` (just 404).

**Comment by tmpfs** [comment]
You are correct, three is not the way to go, thinking some more, my preference is `fetch404` and `fetch410`, then when both need to be handled with the same logic:

```javascript
crawler.on('fetch404', onError)
  .on('fetch410', onError);
```

Done :)

Incidentally, I believe when a 404/410 is encountered the body of the document is not downloaded, is that correct? If so, how should I go about fetching the body content in this situation?

**Comment by fredrikekelund** [comment]
On second thought, I agree with you, fetch404 and fetch410 seems to be the simplest and most consistent way of going about it. Feel free to submit a PR for it, but since it's a breaking change, I'd argue for us to wait a little before merging it. That way we can aggregate a few breaking changes and then bump the major version number

**Comment by tmpfs** [comment]
@fredrikekelund, I agree that makes sense. I just need to write a test for the 410 event and then I think the PR can be submitted. Not much to it ;)

**Comment by tmpfs** [comment]
Oops, the answer to my previous question is in the readme:

https://github.com/cgiffard/node-simplecrawler#a-note-about-http-error-conditions

!

**Comment by fredrikekelund** [comment]
Closing this as #224 was merged
