### ISSUE TITLE
Same domain edge case on different ports

### ISSUE THREAD

**Issue by tmpfs** [cgiffard/node-simplecrawler#221]
Forgive me for raising so many issues but I have been learning `simplecrawler` these past few days and my knowledge is thin.

I have run into an issue where a domain with a different port is being crawled. This is the same domain that I originally crawled so strictly speaking is correct however I wanted to ask how you think this should be handled.

I am testing my service(s) locally running on `localhost:3xxx` (using the same protocol) they are decoupled yet dependent services, one links to the other but the other does not link back.

When I crawl the primary service which links to the secondary service the secondary service is also crawled (which I believe is correct) but I would like to understand the *best way to prevent this*.

Maybe a config property already exists?

If not maybe we could add a property that includes a port comparison when comparing domains, something like `strictSameDomain` that would compare the ports for the parsed url and even if the hostnames are the same but the ports differ to treat it as a separate domain.

Thank you so much for `simplecrawler` (I have been very impressed) and I hope I haven't missed something obvious with this issue.

**Comment by tmpfs** [comment]
Tying to work out how I can achieve this, I set `host` to include the port:

```
 crawler.host = 'localhost:3000';
```

Results in:

```
ERROR | 599 http://localhost:3000:3000/
```

Which appears like a little bug to me that could be fixed. Happy to look into it more if you like?

Maybe when `host` includes a port do not go to other ports on the same domain?

**Comment by cgiffard** [comment]
In this instance, host is explicitly intended to be a resolvable host not including a port number, and it'd be a bit confusing to add additional logic to parse the port out of it — we do offer auto URL deconstruction via the simple instantiation method.

I definitely feel your pain — these kinds of crawl issues can be a bit frustrating to resolve. What resources get fetched and which ones don't is a challenging problem that has seen us introduce a lot of custom logic and flags over the years (!!!).

Ultimately, though, I think that creating any more would be a mistake. Instead, we're moving towards a flexible but simple API which will allow you to quickly incorporate the logic you want without having to modify any simplecrawler code. We made an important step toward that recently with the addition of an additional parameter to our `fetchCondition` API, which should already let you realise your desired behaviour.

https://github.com/cgiffard/node-simplecrawler#excluding-certain-resources-from-downloading

You could prevent port shifts with a fetch condition like the following:

```js
var conditionID = myCrawler.addFetchCondition(function(parsedURL, queueItem) {
    return parsedURLport === queueItem.port;
});
```

Please let me know how that works for you. :)

**Comment by tmpfs** [comment]
> I definitely feel your pain — these kinds of crawl issues can be a bit frustrating to resolve.

No pain, just new to this library so trying to understand how to get what I am looking for :)

> What resources get fetched and which ones don't is a challenging problem that has seen us introduce a lot of custom logic and flags over the years (!!!).

I am learning this at the moment, but I feel that `simplecrawler` should be flexible enough for my needs...although I do have more questions on my mind.

> Ultimately, though, I think that creating any more would be a mistake. Instead, we're moving towards a flexible but simple API which will allow you to quickly incorporate the logic you want without having to modify any simplecrawler code

I think this is a good philosophy, I hope that my questions don't bother you too much ;)

I'll test the code you posted and let you know. Is it worth having a repository/wiki page/documentation for these little helpful tips (or add to the readme)? Might save some trouble in the long run if these questions crop up again?

**Comment by tmpfs** [comment]
Ok, so I tried what you posted and that doesn't work as I wish, then I modified it a little for the logic which I think should work and it's nearly there but I have an issue.

So the logic I want to implement could be described as *only fetch from the same domain disallowing other ports on the same domain*.

I store the `host` and `port` for the initial URL then in the fetch condition I compare `url.host` and `url.port` to the initial host and port. For the most part this appears to work, I see my log statements that indicate that the host/port is being skipped - however, the `fetchcomplete` event is still firing for URLs on the other port.

Because this is difficult to debug I will try to reproduce this in isolation, would you take a look if I set up an isolated test for this?

**Comment by cgiffard** [comment]
If you could establish an isolated test so we can look into the issue, (and start another issue for it) that'd be enormously helpful! Thanks for your patience. :)

**Comment by tmpfs** [comment]
Thanks so much, in isolation I get the expected behaviour and I have an idea what might be the culprit, do fetch conditions fire when manually adding to the queue? The code that does not work has this:

```
    crawler.on('fetchredirect', function(item, url) {
      crawler.queue.add(url.protocol, url.host, url.port, url.path);
    })
```

Going to dig a little deeper...

**Comment by tmpfs** [comment]
Wahoo, success :) My error was not returning the new url but manually adding to the queue!

I changed the redirect to this:

```javascript
crawler.on('fetchredirect', function(item, url) {
  return url;
})
```

And the fetch condition test:

```javascript
return (host === url.host && port === parseInt(url.port));
```

Now works as expected.

As an aside, one thing that jumped out at me testing this is that all events have `queueItem` as the first argument in the signature, whereas fetch conditions buck that trend - would it be worth changing fetch conditions to `(queueItem, parsedURL)`; I know you will likely want to work with the URL more often but consistency is nice - makes things predictable :)

So I guess the important question is: should adding items to the queue manually trigger fetch conditions?

**Comment by cgiffard** [comment]
Regarding your style issue — it's an issue of legacy. It'd be nice to change, but up until now, queueItem wasn't passed to fetchConditions and because all the existing code relies on fetchConditions being passed a parsed URL object as the first parameter, we'd be breaking everything if we changed it. :(

It is certainly a consideration for a new API or future release where we flag breaking changes.

**Comment by tmpfs** [comment]
Makes a lot of sense thanks!

Regarding whether manually queuing items should trigger fetch conditions, I expect it is by design, the assumption being that you know what you are doing when manually adding to the queue and can potentially trigger the fetch conditions yourself. Having said that it does feel very counter-intuitive to me ;)

**Comment by fredrikekelund** [comment]
It's might be easy to trip up on this, but fetch conditions are applied in the `crawler.queueURL` method, which is the standard way of adding URL's, both internally and externally. 

And btw, maybe I'm missing something, but why are you re-adding URL's that were redirected?

Like your idea about the order of arguments to fetch conditions!

**Comment by cgiffard** [comment]
I think we should plan to make a major milestone release with breaking changes, that cleans up the API. (Addressing weird inconsistencies like this.)

**Comment by cgiffard** [comment]
(And as @fredrikekelund points out — unless these redirect URLs were filtered out by the crawler configuration or fetch conditions, they'll be automatically added to the queue.)

**Comment by tmpfs** [comment]
In my experience redirects were not being followed, maybe I am missing some code (you guys are moving fast) but that was the only way for me to get redirects to be followed at the moment.

Should redirects be followed by default? Is there something else I should be doing?

**Comment by fredrikekelund** [comment]
Hmm, I think the source of confusion here might be that the second argument to fetchredirect is the current queueItem, so the URL's you're adding have already been handled. Redirects are handled automatically, but if you need to do something with the target URL for the redirection, look to `response.headers.location` (response being the 3rd argument to the event handler)

**Comment by fredrikekelund** [comment]
Oops, looks like I might've jumped too quick to conclusions there hehe. Will look into this in a couple of hours, but redirects are handled automatically for sure

**Comment by cgiffard** [comment]
Redirects may not be being followed if the crawler configuration is filtering them out. That'd be the first thing I'd check. If you think there's a bug processing redirects, please file an issue about that (and it'd be really helpful if you could provide a test case for it!) :)

**Comment by tmpfs** [comment]
Cool, I'll check it out, likely an error my end but it was one of the first things I noticed when I first started evaluating `simplecrawler`, I hit `google.com` and nothing because they do the regional redirect.

I'll tweak my previous isolation test a little ;)

**Comment by tmpfs** [comment]
Nothing with this (using latest on master from my fork which I believe is in sync with master here):

```
var crawler = new Crawler('google.com', '/', 80);
crawler.on('fetchcomplete', function(item, buf, res) {
  console.dir(item.url); 
})
crawler.start();
```

```
curl -I http://google.com
```

```
HTTP/1.1 302 Found
Location: http://www.google.co.id/?gws_rd=cr&ei=HnzBVvb8AYSjugT3tZygBw
Cache-Control: private
Content-Type: text/html; charset=UTF-8
P3p: CP="This is not a P3P policy! See https://www.google.com/support/accounts/answer/151657?hl=en for more info."
Date: Mon, 15 Feb 2016 07:19:58 GMT
Server: gws
Content-Length: 261
X-Xss-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Set-Cookie: NID=76=AaQ7Uq3u9_cMC383m9cZcv46XOtcCvOMs0r0EvOFURB5tBkTN0pxeykv2LrLNH5ZvTV4ieEC6FTcsBfAvvtQ0bQoHVYT24kX2dhkeItbvAaoCcggEOTnsB3cTMQ5DjjxMJDHbKdpPw; expires=Tue, 16-Aug-2016 07:19:58 GMT; path=/; domain=.google.com; HttpOnly
Connection: close
```

Now you know which country I am in :)

Maybe you are following 301 but not handling 302?

**Comment by cgiffard** [comment]
In this case, the reason is that the `google.co.id` is considered a different hostname to the original domain, and so the redirect will get filtered out and won't be added to the queue.

This is a *really, really common* problem people run into, and I think we should consider adding a troubleshooting guide, with this as the first item, haha. :)

**Comment by tmpfs** [comment]
Thanks for clearing that up! :)

**Comment by tmpfs** [comment]
FYI, I verified this with an isolation test that confirms both 301 and 302 are followed for redirects on the same host :)

I will remove by unnecessary listener and thank you very much for finding my error.
