### ISSUE TITLE
Suggestion: newline delimited JSON in freeze/defrost

### ISSUE THREAD

**Issue by tmpfs** [cgiffard/node-simplecrawler#226]
This would prevent blocking the process and enable writing progress of the freeze/defrost progress to screen. Could be useful for very large crawls.

Very easy to parse as a stream, would require that freeze/defrost become `async` methods.

**Comment by tmpfs** [comment]
Oops, `freeze` is already `async`.

**Comment by tmpfs** [comment]
Good candidate for `setImmediate()`.

**Comment by cgiffard** [comment]
For large crawls I would definitely recommend using a DB-backed queue (like Redis, for instance.) That way you get persistence without worrying about writing to disk. That said, it can't hurt to preserve the queue in better ways.

**Comment by tmpfs** [comment]
Is there are redis backed queue implementation you know of, happy to write one if not, I use redis heavily :)

**Comment by cgiffard** [comment]
I'm not sure. I did see a mongo backed queue some time ago. :)

https://github.com/lzrski/node-simplecrawler-queue-mongo

**Comment by cgiffard** [comment]
(In answer to your question — no, I'm not aware of one. I was thinking of writing one but didn't get around to it, haha.)
