### ISSUE TITLE
Deprecate: queue.getLength()

### ISSUE THREAD

**Issue by tmpfs** [cgiffard/node-simplecrawler#227]
Just don't see what benefit it adds when I can just test `queue.length`.

**Comment by cgiffard** [comment]
Definitely don't use `queue.length`, as it's a synchronous method which will prevent the use of DB-backed queues. Instead, use the callback method always. :)

**Comment by tmpfs** [comment]
Ok, that makes sense - thanks!

Apologies for my lack of understanding ;)
