### ISSUE TITLE
Missing Accept header in request

### ISSUE THREAD

**Issue by dzafel** [cgiffard/node-simplecrawler#228]
I was working with the crawler this morning, tried to crawl a website that is hosted on a Windows machine. Whatever I did the result was always HTTP 500 error, after like an hour I finally found out that the Windows server requires `Accept` header to be set in request, I'm a little surprised that simplecrawler does not set it automatically. I had to add it using:
```
crawler.customHeaders = {
    'Accept': '*/*'
};
```
Shouldn't it be always set by default? Just a question. Thanks!

**Comment by fredrikekelund** [comment]
Hey, thanks for filing an issue! You're right, we should be including that header by default. I realize now that we should add an Accept-Encoding header as well. I'll look into fixing it as soon as possible!

**Comment by fredrikekelund** [comment]
@dzafel I've published a fix to master, you can give it a try if you like
