### ISSUE TITLE
Crawl hanging after a number of resources downloaded, still, with 0.6.2

### ISSUE THREAD

**Issue by cgiffard** [cgiffard/node-simplecrawler#229]
The issue persists! But now, I have a test case given to me by a coworker. After a little bit of anonymisation, I'll throw it up.

**Comment by fredrikekelund** [comment]
:sob:

**Comment by cgiffard** [comment]
My thoughts exactly. I'll chuck the test case up here in a bit. :(

**Comment by tmpfs** [comment]
Yeh, I noticed this as well, not too sure of the trigger, although I did notice (before I implemented strict same domain matching) that it always seemed to happen when moving to a different domain, ie, it finished crawling one domain, hung for quite a while and then continued processing the other domain.

**Comment by tmpfs** [comment]
I have a couple of possible areas for investigation:

* DNS
* Default number of HTTP agents

I think possibly the second, when making many HTTP client requests many sockets can be left open for quite a while before they are actually closed by the OS, I forget the TCP state they are left in, but I have experienced this *hang* before and the solution was to increase the global `maxAgents`.

I think that would be the first thing to try to rule out. Might by worth getting an `lsof -i TCP` dump at the time of the hang too.

I should be able to reproduce this by removing my strict domain matching logic, I'll try to take a look soon.

**Comment by tmpfs** [comment]
Ok, super-interesting. Just reproduced this and what I am seeing is the hang at the end of the crawl - however the logs from my database server are printing requests *during* the hang!

Which would indicate to me, as the log output is happening on `fetchcomplete`, that somehow the `fetchcomplete` event is not firing at the correct time or some other timing issue is present.

**Comment by tmpfs** [comment]
Interestingly the issue is also present with node v4 where they changed the value of `maxSockets` (not `maxAgents` as noted above). But they also added `maxFreeSockets` and set it's value to 256.

I think this is a TCP backlog issue.

**Comment by tmpfs** [comment]
So far I have determined that:

* Setting `Connection: close` has no impact
* Setting `maxSockets` and `maxFreeSockets` has no impact
* Increasing `/proc/sys/net/ipv4/tcp_max_syn_backlog` has no impact
* That the database server logs during the hang does not appear to be a red herring as the web server also logs requests during the hang
* That the hang I experience is actually *at the end of the crawl* not when switching hosts - when I expect `complete` to fire

**Comment by tmpfs** [comment]
Ok, I don't know about other people's experiences but I just got to the bottom of my problem.

I have a website with a lot of 302 redirects which point to another host:port so they would not be followed which means `fetchcomplete` would never fire for those resources by logging on `fetchredirect` as well as `fetchcomplete` the program does not appear to `hang` - it was never really hanging for anyhow, just confusion over the events.

Maybe this is the cause of other people's *hangs*?

**Comment by tmpfs** [comment]
Maybe we need a separate event for *redirect that is not followed*?

**Comment by cgiffard** [comment]
No, the cause is distinctly different — it's not that they're listening to the wrong events, but that the crawl process stops entirely. You can test for this by replacing the `emit` function on the crawler and logging the first argument.

I think an event to show resources that were denied fetching might be useful — `fetchdenied`, etc.

I've been so busy at work that I haven't managed to produce the test case, but I'll do so shortly.

**Comment by Voronchuk** [comment]
Any progress on this one?

**Comment by cgiffard** [comment]
Weirdly enough, the issue happens on my colleague's computer but not mine. We've been busy so only got a chance to look at it yesterday, but it seems like there's a bug where the number of open requests exceeds the defined level of concurrency, somehow.

```
fetchheaders http://www.ntnews.com.au/video/Lifestyle/Food/
fetched 102 of 130 — 3 open requests, 0 open listeners
fetchstart http://www.ntnews.com.au/video/Travel/
fetched 104 of 130 — 1 open requests, 0 open listeners
fetchheaders http://www.ntnews.com.au/video/Travel/
fetched 104 of 130 — 2 open requests, 0 open listeners
fetchstart http://www.ntnews.com.au/news/special-features/+%20src%20+
fetched 105 of 130 — 2 open requests, 0 open listeners
fetchstart http://www.ntnews.com.au/news
fetched 105 of 130 — 3 open requests, 0 open listeners
fetchstart http://www.ntnews.com.au/news/special-features/%28useSSL
fetched 105 of 130 — 3 open requests, 0 open listeners
fetchheaders http://www.ntnews.com.au/news
fetched 106 of 130 — 3 open requests, 0 open listeners
fetchredirect http://www.ntnews.com.au/news
got a redirect for : http://www.ntnews.com.au/news to: www.ntnews.com.au
fetched 106 of 130 — 3 open requests, 0 open listeners
queueduplicate { protocol: 'http',
  host: 'www.ntnews.com.au',
  port: 80,
  path: '/',
  uriPath: '/',
  depth: 4 }
fetched 106 of 130 — 3 open requests, 0 open listeners
fetchstart http://www.ntnews.com.au/news/opinion/+%20src%20+
fetched 106 of 130 — 4 open requests, 0 open listeners
fetchstart http://www.ntnews.com.au/news/opinion/%28useSSL
fetched 106 of 130 — 4 open requests, 0 open listeners
fetchheaders http://www.ntnews.com.au/news/special-features/+%20src%20+
fetched 107 of 130 — 4 open requests, 0 open listeners
fetch404 http://www.ntnews.com.au/news/special-features/+%20src%20+
fetched 107 of 130 — 4 open requests, 0 open listeners
fetchstart http://www.ntnews.com.au/sport/+%20src%20+
fetched 107 of 130 — 5 open requests, 0 open listeners
fetchstart http://www.ntnews.com.au/sport/%28useSSL
fetched 107 of 130 — 5 open requests, 0 open listeners
fetchheaders http://www.ntnews.com.au/news/special-features/%28useSSL
fetched 108 of 130 — 5 open requests, 0 open listeners
fetch404 http://www.ntnews.com.au/news/special-features/%28useSSL
fetched 108 of 130 — 5 open requests, 0 open listeners
fetchstart http://www.ntnews.com.au/lifestyle/+%20src%20+
fetched 108 of 130 — 5 open requests, 0 open listeners
fetchheaders http://www.ntnews.com.au/news/opinion/+%20src%20+
fetched 109 of 130 — 5 open requests, 0 open listeners
fetch404 http://www.ntnews.com.au/news/opinion/+%20src%20+
fetched 109 of 130 — 4 open requests, 0 open listeners
fetchheaders http://www.ntnews.com.au/news/opinion/%28useSSL
fetched 110 of 130 — 4 open requests, 0 open listeners
fetch404 http://www.ntnews.com.au/news/opinion/%28useSSL
fetched 110 of 130 — 4 open requests, 0 open listeners
fetchstart http://www.ntnews.com.au/lifestyle/%28useSSL
fetched 110 of 130 — 5 open requests, 0 open listeners
fetchstart http://www.ntnews.com.au/entertainment/+%20src%20+
fetched 110 of 130 — 5 open requests, 0 open listeners
fetchheaders http://www.ntnews.com.au/sport/+%20src%20+
fetched 111 of 130 — 5 open requests, 0 open listeners
fetch404 http://www.ntnews.com.au/sport/+%20src%20+
fetched 111 of 130 — 5 open requests, 0 open listeners
fetchstart http://www.ntnews.com.au/entertainment/%28useSSL
fetched 111 of 130 — 5 open requests, 0 open listeners
fetchheaders http://www.ntnews.com.au/sport/%28useSSL
fetched 112 of 130 — 5 open requests, 0 open listeners
fetch404 http://www.ntnews.com.au/sport/%28useSSL
fetched 112 of 130 — 5 open requests, 0 open listeners
fetchstart http://www.ntnews.com.au/classifieds/+%20src%20+
fetched 112 of 130 — 6 open requests, 0 open listeners
fetchstart http://www.ntnews.com.au/classifieds/%28useSSL
fetched 112 of 130 — 7 open requests, 0 open listeners
fetchstart http://www.ntnews.com.au/video/+%20src%20+
fetched 112 of 130 — 8 open requests, 0 open listeners
fetchstart http://www.ntnews.com.au/video/%28useSSL
fetched 112 of 130 — 9 open requests, 0 open listeners
fetchstart http://www.ntnews.com.au/realestate/+%20src%20+
fetched 112 of 130 — 10 open requests, 0 open listeners
fetchstart http://www.ntnews.com.au/realestate/%28useSSL
fetched 112 of 130 — 11 open requests, 0 open listeners
fetchstart http://www.ntnews.com.au/business/+%20src%20+
fetched 112 of 130 — 12 open requests, 0 open listeners
fetchstart http://www.ntnews.com.au/business/%28useSSL
fetched 112 of 130 — 13 open requests, 0 open listeners
fetchstart http://www.ntnews.com.au/news/sun-newspapers
fetched 112 of 130 — 14 open requests, 0 open listeners
fetchstart http://www.ntnews.com.au/help/+%20src%20+
fetched 112 of 130 — 15 open requests, 0 open listeners
fetchstart http://www.ntnews.com.au/help/%28useSSL
fetched 112 of 130 — 16 open requests, 0 open listeners
fetchstart http://www.ntnews.com.au/help/home-delivery/

---------- (this is where it hung.) ----------
```

No further events of any kind were emitted.

This is the debugging code I had my colleague throw in his crawler to work out what was going on:

```js
var originalEmit = crawler.emit;
    crawler.emit = function(evtName, queueItem) {
        crawler.queue.complete(function(err, completeCount) {
            if (err) {
                throw err;
            }

            crawler.queue.getLength(function(err, length) {
                if (err) {
                    throw err;
                }

                console.log("fetched %d of %d — %d open requests, %d open listeners".green,
                    completeCount,
                    length,
                    crawler._openRequests,
                    crawler._openListeners);
            });
        });

        console.log(evtName, queueItem ? queueItem.url ? queueItem.url : queueItem : null);
        originalEmit.apply(crawler, arguments);
    };
```

**Comment by cogentParadigm** [comment]
For me it seems to be consistently stopping at URLs that return a 404. I blacklist the URL in a fetch condition and then crawl again and it goes further until it reaches a few more 404s.

**Comment by cgiffard** [comment]
@cogentParadigm Would you mind adding the debug code above and posting the output?

**Comment by cogentParadigm** [comment]
Here is the output. It hangs at the end of this. I have maxConcurrency set to 1. If I now exclude the URL near the end which returned a 404, I will be able to continue past this point.

````
fetchstart http://www.co.adams.co.us/index.aspx?NID=1330
fetched 1648 of 5163 — 1 open requests, 0 open listeners
fetchheaders http://www.co.adams.co.us/index.aspx?NID=1330
fetched 1649 of 5163 — 1 open requests, 0 open listeners
fetchcomplete http://www.co.adams.co.us/index.aspx?NID=1330
fetched 1649 of 5163 — 1 open requests, 0 open listeners
discoverycomplete http://www.co.adams.co.us/index.aspx?NID=1330
fetched 1649 of 5163 — 1 open requests, 0 open listeners
queueduplicate { protocol: 'http',
  host: 'www.co.adams.co.us',
  port: 80,
  path: '/MyAccount/Profile/-1025',
  uriPath: '/MyAccount/Profile/-1025',
  depth: 5 }
fetched 1649 of 5163 — 1 open requests, 0 open listeners
queueduplicate { protocol: 'http',
  host: 'www.co.adams.co.us',
  port: 80,
  path: '/index.aspx?NID=8',
  uriPath: '/index.aspx',
  depth: 5 }
fetched 1649 of 5163 — 1 open requests, 0 open listeners
queueduplicate { protocol: 'http',
  host: 'www.co.adams.co.us',
  port: 80,
  path: '/index.aspx?NID=31',
  uriPath: '/index.aspx',
  depth: 5 }
fetched 1649 of 5163 — 1 open requests, 0 open listeners
queueduplicate { protocol: 'http',
  host: 'www.co.adams.co.us',
  port: 80,
  path: '/index.aspx?NID=35',
  uriPath: '/index.aspx',
  depth: 5 }
fetched 1649 of 5163 — 1 open requests, 0 open listeners
queueduplicate { protocol: 'http',
  host: 'www.co.adams.co.us',
  port: 80,
  path: '/index.aspx',
  uriPath: '/index.aspx',
  depth: 5 }
fetched 1649 of 5163 — 1 open requests, 0 open listeners
queueduplicate { protocol: 'http',
  host: 'www.co.adams.co.us',
  port: 80,
  path: '/rss.aspx',
  uriPath: '/rss.aspx',
  depth: 5 }
fetched 1649 of 5164 — 1 open requests, 0 open listeners
queueadd http://www.co.adams.co.us/index.aspx?NID=1409
fetched 1649 of 5165 — 1 open requests, 0 open listeners
queueadd http://www.co.adams.co.us/index.aspx?NID=275
fetched 1649 of 5166 — 1 open requests, 0 open listeners
queueadd http://www.co.adams.co.us/index.aspx?NID=323
fetched 1649 of 5167 — 1 open requests, 0 open listeners
queueadd http://www.co.adams.co.us/index.aspx?NID=325
fetched 1649 of 5168 — 1 open requests, 0 open listeners
queueadd http://www.co.adams.co.us/index.aspx?NID=346
fetched 1649 of 5168 — 1 open requests, 0 open listeners
queueduplicate { protocol: 'http',
  host: 'www.co.adams.co.us',
  port: 80,
  path: '/index.aspx?NID=706',
  uriPath: '/index.aspx',
  depth: 5 }
fetched 1649 of 5168 — 1 open requests, 0 open listeners
queueduplicate { protocol: 'http',
  host: 'www.co.adams.co.us',
  port: 80,
  path: '/index.aspx?NID=1204',
  uriPath: '/index.aspx',
  depth: 5 }
fetched 1649 of 5169 — 0 open requests, 0 open listeners
crawlstart null
fetched 1649 of 5169 — 1 open requests, 0 open listeners
fetchstart http://adcogov.org/index.aspx?NID=1050
fetched 1649 of 5169 — 1 open requests, 0 open listeners
fetchheaders http://adcogov.org/index.aspx?NID=1050
fetched 1650 of 5169 — 1 open requests, 0 open listeners
fetch404 http://adcogov.org/index.aspx?NID=1050
fetched 1650 of 5169 — 1 open requests, 0 open listeners
fetchstart http://adcogov.org/DocumentCenter/View/8172
fetched 1650 of 5169 — 2 open requests, 0 open listeners
fetchstart http://adcogov.org/DocumentCenter/View/6470
````

**Comment by fredrikekelund** [comment]
@cogentParadigm do you want to try again with the latest `master`? I've pushed a fix that should make the crawler more diligent in destroying response sockets when encountering 404's. I'm not sure that's linked to this issue, but I've previously had trouble with crawls hanging due to encountering too many disallowed Content-Types (see #201), could be that this change would help this problem.

**Comment by cogentParadigm** [comment]
@fredrikekelund it looks like that worked. Thank you

**Comment by fredrikekelund** [comment]
Great to hear :) Not sure if this solves your issue, @cgiffard, but I was kind of worried this would be a never ending bug hunt. With a bit of luck maybe we can close this pretty soon, then

**Comment by cgiffard** [comment]
I'll get my guy to check again. Thanks @fredrikekelund :)

**Comment by cgiffard** [comment]
As an aside to the issue experienced by @thecameronjones, my old colleague from my previous day job sent me an email to say:

> Hi mate, sorry i forgot to reply back on friday. i tested all our sites with the master and it worked like a charm.
> Thanks for fixing it

So I think we must be good (apparently it the bug was reproducible every time.)

**Comment by fredrikekelund** [comment]
@cgiffard fantastic! :smile: Think we can close this ticket then?

**Comment by cgiffard** [comment]
I think so! If anybody has any issues we can open a new one. :)
