### ISSUE TITLE
Can't get this module to work

### ISSUE THREAD

**Issue by bendulum** [cgiffard/node-simplecrawler#235]
I managed to get this module working but only in simple mode and only once.
All subsequent attempts (simple or advanced as below) did not return anything.
The first attempt, which worked, I aborted half way via the console (ran it via gulp).
I tried a fresh install of the module in a different directory, but to no avail.

```
var simplecrawler = require('simplecrawler');
var url = 'http://www.theguardian.com/environment/blog/2009/oct/01/china-cloud-seeding-parade';
var Crawler = new simplecrawler(url);
Crawler
    .on('queueerror', function() {
        console.log('queueerror', arguments);
    })
    .on('fetcherror', function() {
        console.log('fetcherror', arguments);
    })
    .on('crawlstart', function() {
        console.log('crawlstart', arguments);
    })
    .on('fetchcomplete', function() {
        console.log('fetchcomplete', arguments);
    })
    .on('discoverycomplete', function() {
        console.log('fetchcomplete', arguments);
    })
    .on('complete', function() {
        console.log('complete', arguments);
    })
    .start();`
```
Yields:
```
crawlstart {}
complete {}
```
What am I missing?
Could it be that something with the cookies is in a "bad state" after aborting the first run?
I'm using version 0.6.2.
Thanks.

**Comment by fredrikekelund** [comment]
When using advanced mode, the constructor takes the host, initial path and initial port as separate arguments. Or you could pass just the host (not including the protocol) and set the `initialPath`, `initialPort` and `initialProtocol` properties individually on the crawler instance before calling the `start` method. See https://github.com/cgiffard/node-simplecrawler/blob/master/README.md#advanced-mode for more details! Hope that helps!

**Comment by bendulum** [comment]
@fredrikekelund Thanks for the quick reply. I updated the code as follows:
```
var simplecrawler = require('simplecrawler');
var url = 'www.theguardian.com/environment/blog/2009/oct/01/china-cloud-seeding-parade';
var Crawler = new simplecrawler(url);
Crawler.initialPath = "/";
Crawler.initialPort = 80;
Crawler.initialProtocol = "http";
```
Still getting the same results as before in the console.
```
crawlstart {}
complete {}
```
Will this library throw an error in case the host denies the UserAgent string?

**Comment by cgiffard** [comment]
The problem is that you aren't invoking the advanced mode properly. As @fredrikekelund already pointed out, the signature for establishing an advanced mode crawler is different. Please see the linked documentation.

**Comment by cgiffard** [comment]
(The way you're passing the URL, simplecrawler is not breaking it down, and is treating the whole thing as the hostname.)

This should work.

```js
var simplecrawler = require('simplecrawler');
var host = 'www.theguardian.com';
var Crawler = new simplecrawler(host);
Crawler.initialPath = "/environment/blog/2009/oct/01/china-cloud-seeding-parade";
Crawler.initialPort = 80;
Crawler.initialProtocol = "http";
```

**Comment by bendulum** [comment]
@cgiffard How embarrassingly stupid of me. Thanks, it works like a charm!

**Comment by cgiffard** [comment]
No worries. Glad it's working now! :)
