### ISSUE TITLE
Crawl and fetch only resources with content-type 

### ISSUE THREAD

**Issue by vigneshnrfs** [cgiffard/node-simplecrawler#236]
Hi.

Firstly this is awesome.  I am working on a small project and would like to use this package to only crawl and fetch html files, more specifically with content type text/html.

Is it possible to do this with this package?

**Comment by fredrikekelund** [comment]
It's indeed possible. Please refer to [the docs](https://github.com/cgiffard/node-simplecrawler/blob/master/README.md#configuring-the-crawler). You want to edit the crawler properties supportedMimeTypes and downloadUnsupported :+1:
