### ISSUE TITLE
Crawler exception

### ISSUE THREAD

**Issue by liberman08** [cgiffard/node-simplecrawler#240]
Hi guys,
I've been trying up your crawler. I found out that when I'm trying to crawl this
[link](http://www.amazon.com/Educational-Insights-Sneaky-Snacky-Squirrel/dp/B00486ZVC4%3Fpsc%3D1%26SubscriptionId%3DAKIAJLBZH5H3HZQ5IYDA%26tag%3Driviere-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB00486ZVC4)
neither fetchcomplete event triggers nor any timeout/error/complete event.
My guess is that this link makes an exception somewhere in the crawler code.
I'll be very thankfull if you guys check this up. 
Thanks in advance.

**Comment by Alon-Katz** [comment]
Same here, noticed some amazon links made the crawler not responsive. Hope they get it fixed soon.

**Comment by fredrikekelund** [comment]
Hi, I tested the link with simplecrawler 0.6.2 and didn't have any trouble with it. Could you share the code you're using so I can see if there's something weird going on there?

**Comment by liberman08** [comment]
That's my code
`var crawler = new Crawler("www.amazon.com", "http://www.amazon.com/Educational-Insights-Sneaky-Snacky-Squirrel/dp/B00486ZVC4%3Fpsc%3D1%26SubscriptionId%3DAKIAJLBZH5H3HZQ5IYDA%26tag%3Driviere-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB00486ZVC4");
crawler.maxConcurrency = 1;
crawler.maxDepth = 2;
crawler.decodeResponses = true;
crawler.on("fetchclienterror", function(queueItem, errorData) {
    debugger;
});
crawler.on("fetchtimeout", function(queueItem, crawlerTimeoutValue) {
    debugger;
});
crawler.on("fetcherror", function(queueItem, response) {
    debugger;
});
crawler.on("fetch410", function(queueItem, response) {
    debugger;
});
crawler.on("fetch404", function(queueItem, response) {
    debugger;
});
crawler.on("fetchdataerror", function(queueItem, response) {
    debugger;
});
crawler.on("queueerror", function(errorData, URLData) {
    debugger;
});
crawler.on("fetchcomplete", function(queueItem, responseBuffer, response) { 
  // MAIN LOGIC HERE    
});    
crawler.start();`
The crawler doen't trigger any of those events.

**Comment by fredrikekelund** [comment]
It looks like you're passing the entire URL instead of just the pathname as the second argument to the constructor. Try changing it to `/Educational-Insights-Sneaky-Snacky-Squirrel/dp/B00486ZVC4%3Fpsc%3D1%26SubscriptionId%3DAKIAJLBZH5H3HZQ5IYDA%26tag%3Driviere-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB00486ZVC4` and see if that helps

**Comment by liberman08** [comment]
First of all thanks for all the help.
I've tried to send the path as you said but nothing has changed.
I also forogt to mention that I'm working with this library a lot and 99% of the links works fine. I'm always passing the entire url and not just the path as the second param - always works except some links like this one. 
Is there any other way we can handle it? In our current state some of the urls get satck with an endless loop without getting any callback.

**Comment by fredrikekelund** [comment]
I got a few `fetchredirect` as the first events I encountered when trying to crawl this page. It seems you're using a pretty shallow `maxDepth`, what happens if you remove that?

**Comment by liberman08** [comment]
Thanks!! it really solved it

**Comment by fredrikekelund** [comment]
Glad you got it working :+1: By the way, if the crawler indeed encounters a fatal error, that error will propagate and you'll se an error message in your console. If no error shows up, the problem is likely to be something else
