### ISSUE TITLE
Remove port from Host header

### ISSUE THREAD

**Issue by dzafel** [cgiffard/node-simplecrawler#241]
I think `Host` header shouldn't include a port number, I have issues crawling websites on custom https servers, like Zope/ZServer - they just don't allow port number to be in `Host` header. I'm talking about this line: https://github.com/cgiffard/node-simplecrawler/blob/master/lib/crawler.js#L878 I checked how browsers do this and I can't find any that appends port number to `Host` header, so I'm not sure why simplecrawler does this.

I can set my own `Host` header now using `customHeaders` option but it starts to be complicated when a website uses multiple subdomains. A workaround I use now is:
```js
crawl.on('fetchstart', function(item, data) {
    data.headers['Host'] = data.headers['Host'].split(':')[0];
});
```

**Comment by cgiffard** [comment]
Good catch. Easy to pull off!

**Comment by fredrikekelund** [comment]
I've pushed a fix for this, would you like to give the latest master a try and see if it helps, @dzafel?
