### ISSUE TITLE
Test regression on Windows due to #234

### ISSUE THREAD

**Issue by fredrikekelund** [cgiffard/node-simplecrawler#245]
See #234. Use `localhost` domain instead of `0.0.0.0` and complete the test on `fetchstart` event (which makes the fate of the request more or less irrelevant anyway).

**Comment by XhmikosR** [comment]
BTW, we can add Windows testing; just add Appveyor to this repo either you or @cgiffard and ping me to push a test branch.

**Comment by XhmikosR** [comment]
In fact I just [pushed](https://github.com/cgiffard/node-simplecrawler/tree/appveyor) the needed changes. Only thing left is for @cgiffard to add AppVeyor.

**Comment by cgiffard** [comment]
Ready as soon as you're ready to merge it! Thanks for the suggestion.

[![Build status](https://ci.appveyor.com/api/projects/status/9k8bbh2h0l215mkp/branch/master?svg=true)](https://ci.appveyor.com/project/cgiffard/node-simplecrawler/branch/master)

**Comment by XhmikosR** [comment]
@cgiffard: done, pushed to master.

**Comment by cgiffard** [comment]
Looks like it's working great, thanks @XhmikosR!
