### ISSUE TITLE
Option (or bug), should not crawl escaped HTML

### ISSUE THREAD

**Issue by greggman** [cgiffard/node-simplecrawler#247]
Let's say I'm crawling a site of docs. In the HTML for the docs I have

      &lt;a href=&quot;#notexistbutshouldntmatter&quot;&gt;&lt;/a&gt;

As it is simplecrawler will try to crawl that (and of course fail).

Is the the intended behavior?

**Comment by fredrikekelund** [comment]
Kind of, yes. There are a lot of scenarios to account for when looking for resources in a page, and simplecrawler has chosen to use a rather dumb catch-everything approach for its default discovery mechanism.

The discovery mechanism is almost **intended** to be augmented, and it is common to use something like [cheerio](https://npmjs.com/cheerio) to parse pages into a DOM-like structure where you can be sure to get eg. just the actual href attributes of `<a>` elements.

The discovery mechanism is the most common topic that people ask about, and I intend to add some details about the philosophy around it to the README ASAP.

**Comment by cgiffard** [comment]
What @fredrikekelund said. :)

But it might be worth translating HTML entities into their URI-safe versions in future. And sorry about the ambiguity — I really should've added better docs in the first place. Maybe adding an FAQ.md, or TROUBLESHOOTING.md. :)

**Comment by greggman** [comment]
When you say "use something like cheerio to parse pages into a DOM like structure" are you saying that I should first parse a page using cheerio, then get cheerio's output and pass that to simplecrawler?

I guess what I'm asking is how to stop the false positives? I'm trying to scan my docs for broken links but it's reporting links from the sample code which aren't actually links.

So what's the recommended way of either rejecting false positives or preventing them in the first place?

**Comment by cgiffard** [comment]
It's hard to optimise the discovery mechanism for every use case — a broken link checker wants as few false positives as possible, but a site archiver wants to get as much as possible, even extracting content from binary files, and the cost of false positives is low.

So we try to get everything, and offer some key places to tweak the algorithm. [The inbuilt discovery function simply uses a list of naive regex.](https://github.com/cgiffard/node-simplecrawler/blob/master/lib/crawler.js#L161) You could first limit the patterns only to those you know will work for your use case, by customising it like below:

```js
// Tweak as necessary
crawler.discoverRegex = [
    /\s(?:href|src)\s?=\s?(["']).*?\1/ig,
    /\s(?:href|src)\s?=\s?[^"'\s][^\s>]+/ig
];
```

Alternatively, replacing the discovery function with something less naive is an easy operation.

```js
var cheerio = require("cheerio")

crawler.discoverResources = function(resourceData, queueItem) {
    var $ = cheerio.load(resourceData.toString("utf8"));
    return [].slice.call($("[href],[src]"), 0).forEach(function(item) { return item.attribs.href || item.attribs.src; });
};
```
