### ISSUE TITLE
Add a concept of download conditions

### ISSUE THREAD

**Issue by fredrikekelund** [cgiffard/node-simplecrawler#249]
In addition to fetch conditions, a powerful addition would be a flexible system for determining whether or not to fetch the body of a certain resource. I think we could call this concept download conditions.

The idea is similar to fetch conditions, you register handlers that are executed once the headers for a particular resource have been fetched. You the developer are free to synchronously evaluate these headers however you like, and the return value of the handler will determine whether to continue fetching the resource.

We could potentially fire a `fetchprevented` event for resources that are avoided due to download conditions.

This also means we should be able to drop the `fetchWhitelistedMimeTypesBelowMaxDepth` concept, which always seemed very specific to certain use cases to me.

**Comment by fredrikekelund** [comment]
Working on this, should have a PR ready later today!

**Comment by cgiffard** [comment]
Closed by #273. :)
