### ISSUE TITLE
Inject some code before fetching and after fetching resource

### ISSUE THREAD

**Issue by raintears** [cgiffard/node-simplecrawler#251]
Hi, is it possible to inject some code before fetching and after fetching resource? Also, I need to queue url as and when i need to. Is that possible with node-simplecrawler?

**Comment by fredrikekelund** [comment]
Manually queueing URL's is done with the crawler.queueURL method. This is [documented in the README](https://github.com/cgiffard/node-simplecrawler/blob/master/README.md#adding-to-the-queue). 

As for the injecting code before and after fetches, I'm not sure what you mean exactly, but simplecrawler fires a lot of different events for each page fetch. They let the developer eg. get the response body or change the request headers. Please refer to the event documentation for more details on the different events.

**Comment by fredrikekelund** [comment]
The [README](https://github.com/cgiffard/node-simplecrawler/blob/master/README.md#manually-adding-to-the-queue) was recently updated and should hopefully be a bit clearer with regards to how URL's can be added manually.

The [documentation for events](https://github.com/cgiffard/node-simplecrawler#events) should hopefully guide you in the right direction regarding the injecting of code.

Let us know if you have trouble with it!
