### ISSUE TITLE
Can simplecralwer provide resource received information for each crawled page?

### ISSUE THREAD

**Issue by nicholasblexrud** [cgiffard/node-simplecrawler#254]
I'm looking to crawl a website and view the resources (img, js, css) to see if they have successfully loaded. Specifically, I'm trying to crawl a website and check to see what Google Analytics tags are on each page and to see if they are firing correctly.

Casper.js has an [`onResourceReceived`](http://docs.casperjs.org/en/latest/modules/casper.html#onresourcereceived) event that I hoping simplecrawler can replicate. Can simplecralwer provide resource received information for each crawled page?

Example Casper.js code:

```javascript
var casper = require('casper').create({
        verbose: true
});

casper.options.onResourceReceived = function(arg, response){

        // make sure resource has fully loaded and is GA
        if (response.stage === 'end' && (response.url.indexOf('google-analytics') > -1)) {
                console.log(JSON.stringify(response, null, 2));
                console.log(response.status + " = " + response.url);
        }
};


casper.start('http://www.example.com/', function() {
        this.echo(this.getTitle());
});

casper.run();
```

Results:
```text
200 = http://www.google-analytics.com/r/collect?v=1&_v=j41&a=462664566&t=pageview&_s=1&dl=http%3A%2F%2Fwww.example.com%2F&ul=en-us&de=UTF-8&dt=Example Site...
200 = http://www.google-analytics.com/r/collect?v=1&_v=j41&a=462664566&t=pageview&_s=1&dl=http%3A%2F%2Fwww.example.com%2F&ul=en-us&de=UTF-8&dt=Example Site...
200 = http://www.google-analytics.com/r/collect?v=1&_v=j41&a=462664566&t=pageview&_s=1&dl=http%3A%2F%2Fwww.example.com%2F&ul=en-us&de=UTF-8&dt=Example Site...
200 = http://www.google-analytics.com/collect?v=1&_v=j41&a=462664566&t=pageview&_s=1&dl=http%3A%2F%2Fwww.example.com%2F&ul=en-us&de=UTF-8&dt=Example Site%2...
200 = http://www.google-analytics.com/collect?v=1&_v=j41&a=462664566&t=pageview&_s=1&dl=http%3A%2F%2Fwww.example.com%2F&ul=en-us&de=UTF-8&dt=Example Site%2...
```

**Comment by fredrikekelund** [comment]
simplecrawler doesn't differentiate between pages and resources, everything it fetches is treated equally (fires all the same events and is searched for new resources). You can write your own discovery function, though, for example one that only finds resources specified in the href's of `<a`

**Comment by fredrikekelund** [comment]
Sorry about that, submitted too early, there's more stuff coming!

**Comment by nicholasblexrud** [comment]
@fredrikekelund, thanks for the response. I guess my case is a bit more unique in that some of the google analytics requests are within google tag manger or tealium, meaning there isn't any ga code on the page itself. What I'm really looking for are the resources loaded on each page (like chrome's network tab), this would allow me to then filter received request (like casper.js above) by google-analytics - even if the actual script tag doesn't physically live on the page. It looks like simplecrawler can return the source of the page, but does it actually load the dom? Appreciate your help.

**Comment by fredrikekelund** [comment]
Ah, I see. You're right that simplecrawler doesn't load a DOM for any of the resources it fetches. Something like the cheerio module could provide that, but it seems like you would need a complete browser environment - not just the DOM - to make the requests for scripts and execute them etc, so PhantomJS or some wrapper (like CasperJS) is necessary. 


simplecrawler can work together with PhantomJS, but I wouldn't call the integration first class. There are some duplicate efforts in that both simplecrawler and PhantomJS would fetch the page etc, but there's a section on the README on async event listeners that can be used to call something like PhantomJS, and there's an example in the `examples` folder as well. 


It strikes me that if the module that did the fetching of resources was exchangeable as well, this would be less of a problem (although you'd probably still need a pretty custom solution). This idea had been brought up in #244



Från: Nicholas Blexrud

Skickat: torsdag 24 mars 17:55

Ämne: Re: [node-simplecrawler] Can simplecralwer provide resource received information for each crawled page? (#254)

Till: cgiffard/node-simplecrawler

Kopia: Fredrik Ekelund



@fredrikekelund, thanks for the response. I guess my case is a bit more unique in that some of the google analytics requests are within google tag manger or tealium, meaning there isn't any ga code on the page itself. What I'm really looking for are the resources loaded on each page (like chrome's network tab), this would allow me to then filter received request (like casper.js above) by google-analytics - even if the actual script tag doesn't physically live on the page. It looks like simplecrawler can return the source of the page, but does it actually load the dom? Appreciate your help.

**Comment by nicholasblexrud** [comment]
Figured it would be a custom solution. Appreciate your help @fredrikekelund!
