### ISSUE TITLE
Update code inline docs to JSDoc style

### ISSUE THREAD

**Issue by fredrikekelund** [cgiffard/node-simplecrawler#258]
I don't know if what we're currently using has a formalized standard, but I think it'd be good to keep more documentation in the code, and possibly it'd be good to be able to automatically generate documentation from it as well, in which case something like JSDoc might be a good candidate.

**Comment by cgiffard** [comment]
The standard is currently TomDoc, which I like. I'm happy to use JSDoc, but if we can get a TomDoc linter, sticking with TomDoc would be *my* personal preference, since to my eye it looks nicer when you're reading the code. But happy to hear counterpoints to that. :)

**Comment by cgiffard** [comment]
In my most recent project I used ngdocs, but found that the formal documentation wasn't hugely useful. Perhaps here it'll be better to be able to autogenerate API docs.

**Comment by fredrikekelund** [comment]
Ah, I see - well TomDoc looks pretty nice, I didn't realize the comments followed a formal standard. The best module I found for parsing TomDoc comments seems to be [biscotto](https://www.npmjs.com/package/biscotto), but that's unmaintained and only supports CoffeeScript. There's a ticket where JS support has been asked for: https://github.com/gjtorikian/biscotto/issues/47, but it looks like biscotto won't add support for JS. There's of course the possibility of forking it, but for our purposes, I think it'd be easier to change the comments and use an existing tool to generate the docs.

Hmm, what formal documentation are you referring to in your second comment? Wasn't quite clear to me. I haven't used ngdocs, but what standard we use isn't super important to me as long as there's a good tool to parse it.

**Comment by cgiffard** [comment]
I'm fine with either. Ngdoc or jsdoc — both seem pretty reasonable.

**Comment by cgiffard** [comment]
I already ran into a situation where this would be really helpful — we don't currently have documentation for any of our public methods (!!!).

Linking a generated method documentation from the readme would be a good way to bootstrap it!

**Comment by fredrikekelund** [comment]
Just wanted to say that this is in fact underway, I am working on it! It's somewhat tricky to get everything right though, and actually generating a site from the docs will likely highlight some places where we need to change the format of the documentation. But that's an exercise for after the 1.0.0 release
