### ISSUE TITLE
0.7.0 release

### ISSUE THREAD

**Issue by fredrikekelund** [cgiffard/node-simplecrawler#259]
Since 1.0.0 is probably still a month or so away, I'd like to release a 0.6.3 ASAP. For this relase, I'd like us to include:
* #246 
* #234 
* #228 
* #241 

I'm considering #224 as well, but since it's technically API breaking (although in a really minor way), it might make sense to hold off on that one.

**Comment by cgiffard** [comment]
I think, let's call it 0.7 and include #224. :)

Ideally we shouldn't have to muck around building from release branches, or unmerging stuff (etc.) in order to cut a release (if it's not stable we shouldn't merge it in the first place, haha.)

**Comment by fredrikekelund** [comment]
Alright, cool! :+1: 

Sure, but I think in this case it's the mixing of breaking and non-breaking API changes that's the main hassle, not the stability of the stuff that's been merged

**Comment by cgiffard** [comment]
I figure a minor release is appropriate for a minor breaking change. The others are definitely patches. :)

**Comment by fredrikekelund** [comment]
Let's consider #261 for this as well

**Comment by cgiffard** [comment]
Broadly agree — gimme a sec to review your hard work on #261 and we can cut a release. :)

**Comment by lgraubner** [comment]
Also what about the "respectRobotsTxt" option? At the moment it's kinda confusing as it is documented in the readme, but is not implemented in the current release.

**Comment by fredrikekelund** [comment]
I hear you @lgraubner, the 0.7.0 was meant to be an intermediary release before 1.0.0 to get the latest set of changes out before we release 1.0.0 which would include `respectRobotsTxt`. The reason we don't include that in 0.7.0 is because it breaks the existing API by being turned on by default, and the reason we don't release 1.0.0 right away is that we want to aggregate a good set of breaking changes for the 1.0.0 release. 

I've simply been short on time recently, but as soon as I get some time to spend on simplecrawler, releasing 0.7.0 is the topmost item on my list of priorities (it depends on #261 as well, but I think that's ready to be merged)

**Comment by fredrikekelund** [comment]
I've pushed a [branch called 0.7.0](https://github.com/cgiffard/node-simplecrawler/tree/0.7.0) that includes all changes made since 0.6.2 except the robots.txt stuff. I haven't dealt with release branches before, but I think we could merge this branch and then re-revert the last commit (which was a revert of 5f2e751b8ea5ba454882dfe0d91af399901501de). This way we keep the entire release history in `master`.

Because of how long the 0.7.0 release has been delayed, I'll move ahead with this unless tomorrow unless there are any objections?

**Comment by cgiffard** [comment]
@fredrikekelund Looks fantastic. I agree with the re-revert workflow — [I'm a big fan of making sure the git history reflects what really happened!](http://blog.cgiffard.com/on-the-importance-of-manually-maintained-isolation-for-unit-tests-written-in-impure-languages/#workflowandautomation)

I've looked over the commits for 0.7.0 and think we should be good to go. :) Thanks so much.

**Comment by fredrikekelund** [comment]
Cool! :) Just merged #280, will tag the latest commit as 0.7.0 and then publish on npm

**Comment by fredrikekelund** [comment]
Alright, the release is up on npm and I've written some release notes! Thanks to everyone who contributed to this release - @tobli, @thejoshcrawford, @tmpfs, @Autarc and @hbakhtiyor :balloon:  

Next up is 1.0.0! I'll unrevert the robots.txt stuff tonight or as soon as I have time (hopefully sooner than later) and then get on to the async queue methods and the download conditions and deprecation of `crawler.fetchWhitelistedMimeTypesBelowMaxDepth`

**Comment by fredrikekelund** [comment]
Anyone who wants to contribute to any of the targets for the 1.0.0 milestone is more than free to do so btw, would be much appreciated :)

**Comment by cgiffard** [comment]
Rad! Thanks @fredrikekelund! :)
