### ISSUE TITLE
Can't convert response buffer to a string when response is gzipped

### ISSUE THREAD

**Issue by robinparisi** [cgiffard/node-simplecrawler#260]
I'm trying to convert the response buffer to a string but it seems that when response is gzipped, simplecrawler can't decode it.

Here is my playground: 

```
var Crawler = require("simplecrawler");
var crawler = new Crawler("elliptips.info", "/", 80, 100);

crawler.protocol = 'https';
crawler.decodeResponses = true;
crawler.customHeaders = {
    // don't use gzip for testing
    'accept-encoding': null
}
crawler
    .on("crawlstart", function() {
        console.log("Crawl starting");
    })
    .on("gziperror", function(queueItem, error, resourceData) {
        console.log("gzip error: ", error);
    })
    .on("fetchcomplete", function(queueItem, responseBuffer, response) {
        console.log(response.headers);
        console.log(responseBuffer.toString());
        process.exit()
    })
    .on("complete", function() {
        console.log('crawl complete');
    });

crawler.start();
```

When I remove 'accept-encoding' to enable gzip, I get this :

![capture d ecran 2016-04-01 a 15 25 42](https://cloud.githubusercontent.com/assets/570975/14208114/06ac064e-f81e-11e5-9fd6-cf991405cee1.png)

I've tried with multiples websites and always get the same result.

I'm currently on master branch :

package.json
    ....
    "simplecrawler": "cgiffard/node-simplecrawler",
    ....

Edit: I get the same result with or without decodeResponse set to true.

**Comment by fredrikekelund** [comment]
Thanks for the detailed test case! I'll have a look

**Comment by fredrikekelund** [comment]
I think I found the culprit, and you're absolutely right that the response isn't decoded before it's emitted in the fetchcomplete event! This problem probably hasn't come up before since we haven't included the Accept-Encoding header by default until just recently. I'll submit a fix for this during the weekend! Keep an eye on #259 for the next release due before 1.0.0

**Comment by robinparisi** [comment]
Thanks! I'll definitely keep an eye on the next release :)
