### ISSUE TITLE
uri paths are lowercased before being stored in FetchQueue

### ISSUE THREAD

**Issue by prowley** [cgiffard/node-simplecrawler#263]
FetchQueue.prototype.exists and possibly other places has this code:

`var url = (protocol + "://" + domain + port + path).toLowerCase();
`
This lowercases the path which may contain case-sensitive data, not a huge issue but on the scale of the internet, it is out there waiting to bite.

**Comment by cgiffard** [comment]
Good catch!

**Comment by cgiffard** [comment]
I'm struggling to think why I did that. Guess there was some original purpose-specific thing when I first wrote the crawler. Either way — bug!

**Comment by xverges** [comment]
I was about to report that defrosting the queue did not add the urls as lower case to the index...

**Comment by fredrikekelund** [comment]
@xverges hopefully this shouldn't be an issue anymore - URL's won't change shape as they're added to the queue now
