### ISSUE TITLE
how to not count maxDepth for redirects? 

### ISSUE THREAD

**Issue by hbakhtiyor** [cgiffard/node-simplecrawler#265]
i set `maxDepth` to 2, and want to fetch 2 pages, 
but redirections counting the `maxDepth`

e.g. `example.org` redirect to `www.example.org`
       `example.org/path` redirect to `www.example.org/path/`

any ideas how to not count?

**Comment by hbakhtiyor** [comment]
any ideas? :confused:

**Comment by robinparisi** [comment]
Hi @hbakhtiyor,

It seems that this pull request (https://github.com/cgiffard/node-simplecrawler/pull/255) can fix your issue.

**Comment by hbakhtiyor** [comment]
hi @robinparisi, thanks,

any plan to merge it?

**Comment by robinparisi** [comment]
I'm not one of the maintainers but the pull request doesn't have tests so I don't think it will be merged in that state.

**Comment by fredrikekelund** [comment]
How to solve this really depends a lot on your specific situation. If all requests are redirected to a www subdomain, then you might want to either make that domain the initial one, or make use of the `crawler.ignoreWWWDomain` or `crawler.stripWWWDomain` options in a way that's suitable for your specific case.

If you need a more dynamic way of determining what resources are below the maximum depth you want to fetch, then you can make use of more advanced fetch conditions, where you look at the `depth ` property of the provided queueItem and the hostname of the parsedURL. That kind of logic gives you a lot of power to customize what resources are added to the queue, and which ones are avoided

**Comment by thejoshcrawford** [comment]
@hbakhtiyor I just added some tests to it should be on the way to a merge.

**Comment by fredrikekelund** [comment]
#255 has been merged now, hopefully that can solve your issue! Let us know if that's not the case

**Comment by hbakhtiyor** [comment]
thanks,

@fredrikekelund did you re-publish the package?
does the patch work for e.g. `example.org` redirect to `www.example.org` redirect to `www.example.org/` with no count? two redirections

**Comment by fredrikekelund** [comment]
I haven't had a chance to publish a new version to npm, but you can specify the GitHub repo as the source in your package.json to get the latest changes. 

That sounds like a scenario where #255 should help!
