### ISSUE TITLE
how to add a collection of websites to crawling

### ISSUE THREAD

**Issue by hbakhtiyor** [cgiffard/node-simplecrawler#269]
need to add a list of websites for start crawling
e.g. example.com, foo.org, bar.com, ...
how to achieve this? need to initialize crawler for each website?

**Comment by fredrikekelund** [comment]
It depends on how you want to crawl them. If all you're looking to do is to crawl a couple of websites, where the crawls aren't really related, I would advise you to spin up separate instances of simplecrawler.

If you want to allow more than one domain in a single crawl, you can make use of `crawler.domainWhitelist` (see README for more details)
