### ISSUE TITLE
Respect meta robots

### ISSUE THREAD

**Issue by lgraubner** [cgiffard/node-simplecrawler#278]
As the crawler has now an option to respect `robots.txt` it should also be possible to check the `<meta name="robots" content="noindex,nofollow">` tag.
I'm not sure if it's possible/wanted to process the `noindex` part, but the `nofollow` could be respected.

**Comment by cgiffard** [comment]
First of all, thanks for filing an issue — and apologies for the delay in my response! I just started a new gig and it's been really full on — haven't had much time for github in the last month.

This is one of those ones that I think is a really good idea, but I wonder if we can fully respect it without including a proper HTML parser. The `<base>` attribute is the same — from a user perspective it's definitely sensible for us to include support.

There's probably a broader conversation on the direction of `simplecrawler` in general. When it started it was more of a toolkit for building crawlers, but it's slowly becoming a fully featured crawler in its own right (not necessarily a bad thing, but we should be clear on a direction, and then work toward that philosophy.)

I think, given the number of issues we get asking for simplecrawler to support various HTML annotations, that it might be worth incorporating cheerio (and maybe even passing the cheerio document to event listeners.) But I'm happy to be swayed either way. Any thoughts, @fredrikekelund?

**Comment by lgraubner** [comment]
Thanks for your reply. I was thinking about the robots meta tag as the `robots.txt` will be incorporated in the next release and this makes it kinda complete. In general I like the concept of a basic API which can be customized as there are various use cases.
I'd love to see a pluggable option. Something like the base API (as it exists) and a solid "npm install and you are ready to go" crawler. For that case this would have to be seperated explicitly as I already said in #277.

**Comment by cgiffard** [comment]
I don't mind incorporating cheerio, as it's a pretty small dependency (as things go.) But generally the philosophy is to keep things lean.

**Comment by lgraubner** [comment]
I'd love to contribute. The following `discoverRessources` function I'm using for a project relying on `simplecrawler`. It works with `base` tags, robots meta could be easily added I guess.

```JavaScript
function discoverRessources(buffer, queueItem) {
  var $ = cheerio.load(buffer.toString('utf8'));

  // parse links
  var links = $('a[href]').map(function () {
    var href = $(this).attr('href');

    // exclude "mailto:" etc
    if (/^[a-z]+:(?!\/\/)/i.test(href)) {
      return null;
    }

    // remove anchors
    href = href.replace(/(#.*)$/, '');

    // check if link is relative
    if (!/^https?:\/\//.test(href)) {
      var base = $('base').first();
      if (base.length) {
        // base tag is set, prepend it
        href = url.resolve(base.attr('href'), href);
      }

      // handle links such as "../foo", "/foo" etc
      if (/^\.\.?\/.*/.test(href) || /^\/[^\/].*/.test(href)) {
        href = url.resolve(queueItem.url, href);
      }

    return href;
  });

  return links.get();
}
```

I know, this is probably not the right place to show this. But as this is just some consideration I'm just dropping this in.

**Comment by cgiffard** [comment]
Thanks! This is in the roadmap for 1.0, so we'll probably incorporate some derivative of your code then. :)

**Comment by fredrikekelund** [comment]
I'm fine with including this in 1.0.0! I think that what we should do for this milestone though, is to just perform a fairly simple RegExp search from within the default discoverResources method, if `respectRobotsTxt` is true. If we get a match for a `nofollow` meta tag, we should just return an empty array.

I might have some time to whip up a PR this weekend, but if any of you two have time, feel free to submit one before me!
