### ISSUE TITLE
how to just download pdf files of one site? my configuration below doesn't download any file.

### ISSUE THREAD

**Issue by postgetme** [cgiffard/node-simplecrawler#279]
```
crawler.addFetchCondition(function(parsedURL, queueItem) {
  return parsedURL.path.match(/\.pdf$/ig);
});

crawler.cache = new Crawler.cache('./pdf-files');
```

**Comment by fredrikekelund** [comment]
Hi, could you expand a bit on what sure you're crawling and what result you're trying to achieve? It looks the the fetch condition you're using permits the crawler only to download PDF files, so if you want to find links to PDF files in normal HTML pages, then you need to drop the fetch condition. You could maybe determine if the downloaded file is a PDF in the fetchcomplete event handler instead?

**Comment by postgetme** [comment]
hi, I want the crawler download all pdf files from a giving root url(eg: http://amozon.com) to a directory(eg: ./pdf-files). By your suggestion(drop the fetch condition, download pdf files in fetchcomplete event handler), it works, thank you!

**Comment by fredrikekelund** [comment]
Great to hear!
