### ISSUE TITLE
Discover link with spaces

### ISSUE THREAD

**Issue by furester** [cgiffard/node-simplecrawler#282]
I have an issue when the link discovered contains spaces it seems that `simplecrawler` put in the queue only the first part of the url (it stops at the first space).

for example, I was testing crawler on this page: `https://www.tinoleggio.it/Grecia/Ovest%20Grecia/noleggio-auto-Aktion%20Aeroporto%20%28PVK%29.html` that contains a link to: "`https://www.tinoleggio.it/Grecia/Ovest Grecia/noleggio-auto-Agrinio Aeroporto (AGQ).html`" (for example), the `queueItem` i get is only: "`https://www.tinoleggio.it/Grecia/Ovest`" and subsequently i get a 404 when it tries to fetch that url.

edit: I tried with `crawler.decodeResponses = true;` also, but i've same issue.

**Comment by cgiffard** [comment]
Simplecrawler will queue *both* the URL demarcated by spaces, as well as the entire URL demarcated by quotes. This is as a result of its optimistic discovery algorithm, which tries to discover as many URLs as possible, at the cost of discovering some junk ones.

Would you mind checking that in *addition* to the URL broken by spaces, the entire URL isn't also queued? You can double check by adding the [debugging code sample given in the FAQ — last item](https://github.com/cgiffard/node-simplecrawler#faqtroubleshooting) and paying attention to the `queueadd` and `discoverycomplete` events. If you post the output here, we'll have a better idea of what's going on.

Thanks — and thanks once again for filing an issue. :)

**Comment by furester** [comment]
Thank you @cgiffard i didn't understand how optimistic is. I confirm that there are both links:

```
[..]
queueadd https://www.tinoleggio.it:80/Italia/Lombardia/noleggio-auto-%20Milano%20Stazione%20Porta%20Garibaldi.html
[..]
queueadd https://www.tinoleggio.it:80/Italia/Lombardia/noleggio-auto-
[..]
```

Now i'll figure out how to skip links with spaces (if you have any tips i'll appreciate that), 'cause they are known broken links.

I think we could close this as issue. Thank you very much for the great work!
