### ISSUE TITLE
Crawler stops and wont continue on one domain

### ISSUE THREAD

**Issue by ahansson89** [cgiffard/node-simplecrawler#285]
The domain in question is: http://11live.com

**Comment by ahansson89** [comment]
Does not get further than fetchstart with debugging enabled.

**Comment by cgiffard** [comment]
Hi! Thanks for filing an issue. Could you share the crawler instantiation code so that we might reproduce the issue ourselves?

**Comment by cgiffard** [comment]
Hi @ahansson89 — is this issue still a problem for you?

**Comment by fredrikekelund** [comment]
@ahansson89 it seems there aren't any internal links on the frontpage of http://11live.com/. The crawler only follows links to the same domain by default. If you want it to continue on to other domains, you can set `crawler.filterByDomain = false`.

If you want to crawl multiple domains, but not the entire Internet, you can use [fetch conditions](https://github.com/cgiffard/node-simplecrawler#adding-a-fetch-condition) to write more sophisticated logic for which domains to crawl and which to avoid.
