### ISSUE TITLE
query string is being skipped from initialUrl

### ISSUE THREAD

**Issue by yanalavishnu** [cgiffard/node-simplecrawler#295]
- [x] I have read the contributing guidelines.

If the `initialUrl` is having query params, those are being skipped. As the content of the page changes with the query params, query params should not be skipped.

Sample initialUrl = 'example.com/?query=something'.

**Comment by fredrikekelund** [comment]
Great catch, @yanalavishnu! I assume you're using the latest `master`?

**Comment by yanalavishnu** [comment]
I have used `0.7.0` version code in my project. In that version I have used quickcrawl method which is deprecated. `quickcrawl` method is also skipping query params.

> new Crawler(url.hostname(), url.path() || (url.protocol() === "https" ? 443 : 80));

**Comment by fredrikekelund** [comment]
You're right, quickcrawl is deprecated, but the problem would be the same with the latest master. Will push a fix for this later today!

**Comment by cgiffard** [comment]
Fixed by #296.

**Comment by yanalavishnu** [comment]
@fredrikekelund is `v0.7.0` not being maintained? if so, change the url.path() in 66th line of  to `(url.query() ? url.path()+'?'+url.query():url.path())`

**Comment by cgiffard** [comment]
@yanalavishnu Is it imperative for your purposes that we backport this fix to `0.7.0`? I'm happy to make a new branch for `0.7.1`, but this isn't usual practice for us.

**Comment by yanalavishnu** [comment]
@cgiffard Yes, it is important for my project. I have created branch 0.7.1 and made a pull request, but it is showing merge conflicts and All checks failed. That's why I have requested fredrikekelund to change the code.

**Comment by fredrikekelund** [comment]
@yanalavishnu would it work for you to simply use the regular constructor and pass the path + query string as the `initialPath` parameter? That might be the easiest solution for everyone involved until 1.0.0 is released (which is finally going to happen very soon)
