### ISSUE TITLE
HTTPS crawling does not work.

### ISSUE THREAD

**Issue by LeiZeng** [cgiffard/node-simplecrawler#300]
- [x] I have read the contributing guidelines.

### What happened (Observed behaviour)
(Version 0.7)
When I try to crawl a HTTPS site, like 'https://github.com/', it always triggers redirect, but never hit the site.
I tracked to the `processURL` method, the return value always use `80` as default port, even it's HTTPS protocol, the request host will re-format into `https://github.com:80`, which cause redirect from Github.

### What should happen (Expected behaviour)
HTTPS site should be crawl as well.

### Steps to reproduce the problem (include code examples)
```
const crawler = new Crawler('github.com', '/', 443);
crawler.initialProtocol = 'https'
crawler
    .on('fetchredirect', (queueItem, parsedURL, response) => {
        console.log('URL Redirected from: ', queueItem.url, ' to ', response.headers.location)
    })
   .start()
// only '/' has been crawled.
```

**Comment by cgiffard** [comment]
Hi — thanks for filing an issue. There was a recently fixed problem with initial port assignment — have you tried the version from `master`? It's tracking a bit ahead of the version in npm yet (we are not yet ready to release `1.0`.)

**Comment by LeiZeng** [comment]
Great! Looking forward to it.

**Comment by cgiffard** [comment]
@LeiZeng I see you closed the issue — did `master` work for you? Apologies for the hassle — we'll be releasing soon.
