### ISSUE TITLE
Initial URL skipped when other URL's queued manually before starting crawl

### ISSUE THREAD

**Issue by fredrikekelund** [cgiffard/node-simplecrawler#304]
- [x] I have read the contributing guidelines.

### What happened (Observed behaviour)
When manually queuing URL's before the crawl is started, the initial URL is never added to the queue.

### What should happen (Expected behaviour)
The initial URL should be added to the queue.

### Steps to reproduce the problem (include code examples)
```js
var crawler = new Crawler("http://localhost");
crawler.queueURL("http://localhost/test");

crawler.on("fetchcomplete", function(queueItem) {
    console.log("fetched", queueItem.url);
});

crawler.on("complete", function() {
    crawler.queue.getLength(function(error, length) {
        // length will be 1, even though it should be 2
        console.log("length", length);
    });
});

crawler.start();
```

**Comment by fredrikekelund** [comment]
@cgiffard let me know if I'm getting ahead of myself here, but this seemed like more intuitive behavior!

**Comment by cgiffard** [comment]
Sure, I think this is reasonable! If we get complaints we can always change it back. I wonder if we could make a way of not specifying the initial URL, so we can just go:

```js

var crawler = new Crawler();
myInitialList.forEach(crawler.queueURL.bind.crawler);

...

crawler.start();
```
