### ISSUE TITLE
Make crawler.queueURL take a callback

### ISSUE THREAD

**Issue by fredrikekelund** [cgiffard/node-simplecrawler#305]
`crawler.queueURL` currently doesn't take a callback, even though it's asynchronous. We should have it take one to enable asynchronous queue implementations.

**Comment by fredrikekelund** [comment]
Hmm maybe I was a bit hasty here, I didn't think about the events that this method emits... When the developer uses this method manually, a callback might make sense, seeing as it's a single operation. But at the same time, you're not really interested in getting any data back, you just want to hand the URL to the crawler and wait for it to be fetched. So actually, never mind this, I'm jumped on it a bit too quickly! :pensive:

**Comment by cgiffard** [comment]
Yeah, I think queueUrl shouldn't take a callback, since you'll get events back when it's done.
