### ISSUE TITLE
Pass custom variable to queueItem

### ISSUE THREAD

**Issue by ahansson89** [cgiffard/node-simplecrawler#316]
I would like to pass a custom var, such as an ID from my custom built queue on the queueItem in order to use it later. Can someone give an example on how to do that? Thanks.

**Comment by fredrikekelund** [comment]
Hi! If all you're looking to store on the queue item is an ID, then the imminent version 1.0.0 of simplecrawler will assign just that to queue items as a standard. It does that in the queue implementation though, simply by setting a unique `id` property on the queue item in the FetchQueue#add method.

If you're writing a custom queue implementation then that's where to set an ID on queue items: in the queue's `add` method. You could theoretically set more properties than just `id` as well, so long as all the properties described in the [README](https://github.com/cgiffard/node-simplecrawler#queue-items) are there.

Hope that helps!

**Comment by ahansson89** [comment]
I am not sure that I understand.

Right now I am using:
crawler.queue.add('http', example.com, 80, '', 1); 

So how would I pass another var into the queueItem

**Comment by fredrikekelund** [comment]
Ah sorry, my mistake - that's also an upcoming change to the `crawler.queue.add` method - it now accepts a complete queue item as the first argument instead of the separate queue iten parts. That should make it pretty straightforward to add custom properties to queue items!

The 1.0.0 release should land within a week, but you can try out the master branch until then!

**Comment by cgiffard** [comment]
Closed as this is coming in 1.0 — but currently available in master. Feel free to reply on the issue if you want usage help. :)

**Comment by ahansson89** [comment]
Can you give me an example of a complete queue item that goes into the queue.add function?

**Comment by ahansson89** [comment]
When I just do crawler.queue.add('http://example.com') I get an error. If I do crawler.queueURL('http://example.com') I get an error too.

If I do 
var queueItem = { url: 'http://example.com' }; crawler.queue.add(queueItem); I get another error.

**Comment by ahansson89** [comment]
TypeError: callback is not a function
    at addToQueue

**Comment by ahansson89** [comment]
Okay, figured it out. Ended up doing it like this:

`var queueItem = crawler.processURL('http://example.com');
queueItem.custom_var = 'custom';
crawler.queue.add(queueItem, 'force', function(error) {
	if (error) {
		console.log(error);
	}
});`

**Comment by fredrikekelund** [comment]
Good to hear you got the hang of it! Just a quick note on your last example - the second argument to `crawler.queue.add` is a boolean  (ie. true/false), not a string
