### ISSUE TITLE
Can not fetch the correct page after login with cookies 

### ISSUE THREAD

**Issue by hanwencheng** [cgiffard/node-simplecrawler#323]
Hi, thanks for the convenient library and detailed documentation,

I followed carefully with the Login part in [troubleshooting](https://github.com/cgiffard/node-simplecrawler/blob/master/README.md#L704), I could get the login success response, but I cannot fetch the page as login user, i.e. the fetched page still display the information without login.

### What happened (Observed behaviour)

The code I use is 
```
var Crawler = require("simplecrawler"),
    request = require("request");

var crawler = new Crawler("https://example.com/");

request.post("https://example.com/login", {
    form: {
        username: "iamauser",
        password: "supersecurepw"
    }
    jar: true,                //according to request library, jar is needed for getting the cookies
    encoding : null,     //for decoding chracters
}, function (error, response, body) {
    crawler.cookies.addFromHeaders(response.headers["set-cookie"]);
    console.log("cookies are", response.headers["set-cookie"])//showing later
    crawler.start();
});

crawler.on("fetchcomplete", function (queueItem, responseBuffer, response) {
    console.log("Fetched", queueItem.url);
});
```
Here is the cookies from the console:

```
[ 'kMpW_2132_saltkey=o2Jc63jR; expires=Sat, 24-Sep-2016 16:01:57 GMT; path=/; httponly',
  'kMpW_2132_lastvisit=1472137317; expires=Sat, 24-Sep-2016 16:01:57 GMT; path=/',
  'kMpW_2132_sid=jiyEIy; expires=Fri, 26-Aug-2016 16:01:57 GMT; path=/',
  'kMpW_2132_lastact=1472140917%09member.php%09logging; expires=Fri, 26-Aug-2016 16:01:57 GMT; path=/',
  'kMpW_2132_ulastactivity=865eVM8Jzjc4AQzmvzUoaSnRndbjY%2BU%2BKYneWnsr8m%2Bw0Sxaedzm; expires=Fri, 25-Aug-2017 16:01:57 GMT; path=/',
  'kMpW_2132_sid=jiyEIy; expires=Fri, 26-Aug-2016 16:01:57 GMT; path=/',
  'kMpW_2132_auth=750eMJtdXXHVqFrT85nxcfQ2MTuLzpTMrixIq4r0PcH4MwOmcarEs9qU3tHoVP7UDIpmEIDLNhuZiaWzTWz8BPemxME; path=/; httponly',
  'kMpW_2132_loginuser=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/',
  'kMpW_2132_activationauth=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/',
  'kMpW_2132_pmnum=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/',
  'kMpW_2132_lastcheckfeed=234353%7C1472140917; expires=Fri, 25-Aug-2017 16:01:57 GMT; path=/',
  'kMpW_2132_checkfollow=1; expires=Thu, 25-Aug-2016 16:02:27 GMT; path=/',
  'kMpW_2132_lip=92.206.51.54%2C1472140695; path=/',
  'kMpW_2132_myrepeat_rr=R0; expires=Fri, 26-Aug-2016 16:01:57 GMT; path=/' ]
```

I already spent one day in this problem, and I also check the source code of simplecrawler, please help!

### What should happen (Expected behaviour)
Should be able to fetch the pages after login, as I state before.

### Steps to reproduce the problem (include code examples)

Post URL is here (with a post-form) : 
"http://dolc.de/member.php?mod=logging&action=login&loginsubmit=yes&infloat=yes&lssubmit=yes&inajax=1"

**Comment by fredrikekelund** [comment]
Hmm, it does look like the example doesn't work as expected. I'll have a look at this tomorrow!

**Comment by fredrikekelund** [comment]
Alright, so different sites handle login sessions a bit differently, but one potential pitfall is [CSRF](https://en.wikipedia.org/wiki/Cross-site_request_forgery) tokens.

I assume you're trying to crawl http://dolc.de? Since the site appears to be in Chinese (or at least that's what Chrome tells me), I can't tell for sure what the different inputs in the login form do, but after a bit of experimenting, I came up with a solution that helped me when I tried to crawl a different site that required a login just now.

Let me know if this fixed your problem!

```js
var Crawler = require("simplecrawler"),
    cheerio = require("cheerio"),
    request = require("request");

var crawler = new Crawler("https://example.com/");

request("https://example.com/login", {
    // The jar option isn't necessary for simplecrawler integration, but it's
    // the easiest way to have request remember the session cookie between this
    // request and the next
    jar: true
}, function (error, response, body) {
    // Start by saving the cookies. We'll likely be assigned a session cookie
    // straight off the bat, and then the server will remember the fact that
    // this session is logged in as user "iamauser" after we've successfully
    // logged in
    crawler.cookies.addFromHeaders(response.headers["set-cookie"]);

    // We want to get the names and values of all relevant inputs on the page,
    // so that any CSRF tokens or similar things are included in the POST
    // request
    var $ = cheerio.load(body),
        formDefaults = {},
        // You should adapt this selector so that it only targets inputs from
        // the login form
        loginInputs = $("input");

    // We loop over the input elements and extract their names and values so
    // that we can include them in the login POST request
    loginInputs.each(function(i, input) {
        var inputName = $(input).attr("name"),
            inputValue = $(input).val();

        formDefaults[inputName] = inputValue;
    });

    // Time for the login request!
    request.post("https://example.com/login", {
        // We can't be sure that all of the input fields have a correct default
        // value. Maybe the user has to tick a checkbox or something similar in
        // order to log in. This is something you have to find this out manually
        // by logging in to the site in your browser and inspecting in the
        // network panel of your favorite dev tools what parameters are included
        // in the request.
        form: Object.assign(formDefaults, {
            username: "iamauser",
            password: "supersecretpw"
        }),
        // We want to include the saved cookies from the last request in this
        // one as well
        jar: true
    }, function (error, response, body) {
        // That should do it! We're now ready to start the crawler
        crawler.start();
    });
});

crawler.on("fetchcomplete", function (queueItem, responseBuffer, response) {
    console.log("Fetched", queueItem.url, responseBuffer.toString());
});
```

**Comment by hanwencheng** [comment]
Thanks @fredrikekelund,  it's very detailed.

I understand the idea now, is it pretend to be a web user with cookies before post the login form? 

And I tried the origin code and integrate to my code, it seems it did not work, I am not sure it is the problem of CSRF. I noticed that `addFromHeaders ` is only called once here after first request, is that right? Anyway I also tried use it in other steps, and it failed either.

I share you my repository with some login information, main entry is `index.js` maybe you can have a try with command `node index 1`, it's almost the plain code from you and the simplecrawler's example.

**Comment by fredrikekelund** [comment]
Yep, that's the idea! We need to emulate the way a browser behaves with cookies when logging in. I've updated the login example in the README to the code I submitted in my previous comment. Hopefully that will help people who bump into similar problems in the future.

I might have one extra look to make sure that the problems you're having isn't a result of some bug in simplecrawler, but I'll go ahead and close this issue after that. Let us know if you have any more problems related directly to simplecrawler!

**Comment by hanwencheng** [comment]
I have checked the cookie jar in the repository, it seems update the cookies all correctly, but I am not sure if it should update the cookie according to the path [source here](https://github.com/cgiffard/node-simplecrawler/blob/master/lib/crawler.js#L1280).

Now I use request, which integrate a [global cookie jar](https://github.com/request/request/blob/master/lib/cookies.js) with [tough cookie](https://github.com/SalesforceEng/tough-cookie), it works for me now when I create my simple crawler with request. 

I have not go into the detail of this repository, because I am not so familiar with cookies, but I will continuing watch this issue, and you may use my repository as a test.

**Comment by fredrikekelund** [comment]
We ended up figuring out that this was due to the fact that we made different requests both over HTTP and HTTPS to the site, right? Feel free to re-open this otherwise @hanwencheng
