### ISSUE TITLE
Is there any way to clear the queue?

### ISSUE THREAD

**Issue by ahansson89** [cgiffard/node-simplecrawler#324]
I want my crawler to iterate a number of times and clear the queue for each iteration. Can you show me an example on how to do that?

**Comment by fredrikekelund** [comment]
What do you want to iterate over? A set of pages or an entire site? And is it necessary to clear the queue, or do you just need to re-queue a set of URL's?

**Comment by ahansson89** [comment]
Clearing the queue completely is the best option for my use case

**Comment by cgiffard** [comment]
There's no inbuilt method to clear the queue, but you can easily assign a fresh queue (and allow the old one to be garbage collected) like this:

```js
// When resetting
mycrawler.queue = new Crawler.queue()
```

Let me know if that satisfies your use case!

As an aside — and in the interests of understanding what features we should prioritise, if you wouldn't mind sharing why you want to clear the queue, it'd be much appreciated! I'm very curious. :)

**Comment by cgiffard** [comment]
Hey, just closing this issue. If my comment above didn't help, and you're still in need of something different, feel free to reopen the issue with a bit more detail. :)

**Comment by mike-aungsan** [comment]
About to open feature request issue and found this.. IT works. Many Thanks

**Comment by mike-aungsan** [comment]
@cgiffard 

My previous comment might be wrong or I miss something when I refactor the code.
I try to reuse the module, give a new path and craw.

var crawler = new Crawler("http://www.example.com/");

// repeat this
function craw(path) {
    crawler.initialPath = path;
    crawler.queue = new Crawler.queue();
    crawler.start();
}

//
craw('/Category.aspx?category=abc');
craw('/Category.aspx?category=xyz');

It does not grab different url. It only pull the first URL.

**Comment by cgiffard** [comment]
@mike-aungsan You might be better off making a new crawler for each crawl, if you're trashing the queue each time.

**Comment by mike-aungsan** [comment]
@cgiffard  Many Thanks.
