### ISSUE TITLE
Request path contains unescaped characters

### ISSUE THREAD

**Issue by ahansson89** [cgiffard/node-simplecrawler#327]
This is what I get:

```
_http_client.js:53
    throw new TypeError('Request path contains unescaped characters');
    ^

TypeError: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:53:11)
    at Object.exports.request (http.js:31:10)
    at /Users/aleksanderhansson/Dropbox/Developer/sites/wpsmarter.dev/scripts/scripts/node_modules/simplecrawler/lib/crawler.js:1118:36
    at FetchQueue.update (/Users/aleksanderhansson/Dropbox/Developer/sites/wpsmarter.dev/scripts/scripts/node_modules/simplecrawler/lib/queue.js:226:9)
    at Crawler.fetchQueueItem (/Users/aleksanderhansson/Dropbox/Developer/sites/wpsmarter.dev/scripts/scripts/node_modules/simplecrawler/lib/crawler.js:1096:19)
    at /Users/aleksanderhansson/Dropbox/Developer/sites/wpsmarter.dev/scripts/scripts/node_modules/simplecrawler/lib/crawler.js:1693:25
    at FetchQueue.oldestUnfetchedItem (/Users/aleksanderhansson/Dropbox/Developer/sites/wpsmarter.dev/scripts/scripts/node_modules/simplecrawler/lib/queue.js:247:13)
    at Crawler.crawl (/Users/aleksanderhansson/Dropbox/Developer/sites/wpsmarter.dev/scripts/scripts/node_modules/simplecrawler/lib/crawler.js:1645:19)
    at Timeout.wrapper [as _onTimeout] (timers.js:417:11)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

```

Maybe we should implement a link checker before the link is passed to request?

**Comment by cgiffard** [comment]
Hey, thanks for filing an issue.

FWIW, there already is a link validator — links are normalised both internally *and* passed through URI.js. This suggests a bug in one of those.

Can you provide the URI which caused the issue?

**Comment by fredrikekelund** [comment]
Closing this for now. Let us know if this issue persists/-ed, @ahansson89!

**Comment by guidodizi** [comment]
Hey @fredrikekelund , how is it going?

I'm still having this issue. It seems that some characters are not escaped.
Here is a simple use case:

    import Crawler from 'simplecrawler'

    const startUrl = "https://corporate.qiagen.com/investor-relations/events-and- 
    presentations/2019/analyst-and-investor-day-2019";

    const crawler = new Crawler(startUrl);
    crawler.start();`

The crawler is finding here a url with a path `/investor-relations/events-and-presentations?name=Analyst+and+Investor+Day+2019#events_Start Date=20190101|20191231&events_o=Start Date,Descending`
This path contains spaces so it breaks down with the same error as stated before

I managed to fix the issue by adding a decode-encode on the url path on `crawler.js` at line `796` npm version `1.1.8`. Here is a snippet of the provisional fix on `Crawler.prototype.processURL`

    Crawler.prototype.processURL = function (url, referrer) {
        var newUrl,
            crawler = this;

        if (typeof referrer !== "object") {
            referrer = {
                url: crawler.initialURL,
                depth: QUEUE_ITEM_INITIAL_DEPTH - 1
            };
        }

        // If the URL didn't contain anything, don't fetch it.
        if (!(url && url.trim().length)) {
            return false;
        }

        // Check if querystring should be ignored
        if (crawler.stripQuerystring) {
            url = uri(url).search("").href();
        }

        // Canonicalize the URL by sorting query parameters.
        if (crawler.sortQueryParameters) {
            url = uri(url).query(function (data) {
                var _data = {};
                Object.keys(data).sort().forEach(function (key) {
                    _data[key] = data[key];
                });
                return _data;
            }).href();
        }

        if (crawler.stripWWWDomain && url.match(/https?:\/\/(www\.).*/i)) {
            url = url.replace("www.", "");
        }

        try {
            // ADDED
            url = encodeURI(decodeURI(url))
            newUrl = uri(url).absoluteTo(referrer.url).normalize();

            if (crawler.urlEncoding === "iso8859") {
                newUrl = newUrl.iso8859();
            }
        } catch (e) {
            // Couldn't process the URL, since URIjs choked on it.
            return false;
        }

        // simplecrawler uses slightly different terminology to URIjs. Sorry!
        return {
            host: newUrl.hostname(),
            path: newUrl.resource(),
            port: newUrl.port(),
            protocol: newUrl.protocol() || "http",
            uriPath: newUrl.path(),
            url: newUrl.href(),
            depth: referrer.depth + 1,
            referrer: referrer.url,
            fetched: false,
            status: "created",
            stateData: {}
        };
    };
    

This is probably not the place nor best way to solve this issue, but we are needing a fix on this.

Thanks for your attention!!
