### ISSUE TITLE
Fix for meta-robots handling

### ISSUE THREAD

**Issue by Abromeit** [cgiffard/node-simplecrawler#328]
Hello there,

i found that PR https://github.com/cgiffard/node-simplecrawler/pull/315 was missing an important case: 
Handling of Meta-Robots Tags which contain more than one statement. 
E.g.: `<meta name="robots" value="noindex, nofollow" />`

I was fiddling around with your Meta-Tag RegExps anyway, 
so why not adding two more lines.

Have a look at [/Abromeit-patch-1](https://github.com/Abromeit/node-simplecrawler/commits/Abromeit-patch-1), if you like to, and Cherry-Pick what you need. 

Maybe there's a fix for existing issues with encoding or sth. as well, dunno. In fact i just wanted to kill some minutes for fun. Which means the Code is untested etc. and therefore you see  an issue here and not a PR :)

<i>
PS: 
I remember when i found this project several years ago 
...and now look at this! I'm totally amazed by what you built here.
Keep up the good work!  ♥
</i>

**Comment by fredrikekelund** [comment]
Thanks for the contribution and for the kind words, I know both I and @cgiffard appreciate it :) Things have slowed down a bit since the 1.0 release, but this is definitely a bug - I hope to be able to look into it this weekend!
