### ISSUE TITLE
Amazon urls response 503

### ISSUE THREAD

**Issue by Alon-Katz** [cgiffard/node-simplecrawler#329]
Hello,
Lately I've noticed that when trying to crawl amazon urls the crawler is getting 503 status code in response and emits fetch error. I've tried getting to the urls manually and it all worked fine. It all worked perfect till last month. The crawler version I'm using is - 1.0.1
Here's a code snippet which rarely works now:

```js
var crawler = new Crawler("http://www.amazon.com/ZenFone-Laser-Unlocked-Smartphone-Storage/dp/B015AH8TQE%3Fpsc%3D1%26SubscriptionId%3DAKIAJLBZH5H3HZQ5IYDA%26tag%3Driviere-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB015AH8TQE");
    crawler.maxConcurrency = 1;
    crawler.decodeResponses = true;
```

The response from the fetch error event is:
![image](https://cloud.githubusercontent.com/assets/7746785/18848392/d0bdd10c-8436-11e6-838c-6e8da2e6316c.png)

**Comment by cgiffard** [comment]
Hi @Alon-Katz — thanks for filing an issue. Had you been using 1.0.1 previously, and it had been working fine?

**Comment by Abromeit** [comment]
Afais that's one of Amazons' many bot protection features. 

Some of the things you could do:
Scrape slower. Introduce some randomness. Use a Common, modern User-Agent. Use multiple IPs.

(But of course you won't b/c scraping data from Amazon is against their TOS. So instead you are going to use the [https://affiliate-program.amazon.com/gp/advertising/api/detail/main.html](Amazon Product Advertising API), I'm sure  ;)

**Comment by Alon-Katz** [comment]
Thanks for the information, I tried using the api but its missing the most basic option, to know the stock
of an item so you wont publish out of stock items in your webiste :(

Hi @cgiffard :), I have been using an older version around the 0.6.2 and when I started geting
the 503 I have upgraded to the latest, but as @Abromeit said its amazon bot protection :(

btw the crawler is amazing, thanks for all the hard work.

**Comment by cgiffard** [comment]
Best thing to do would be to try and change the user agent to something believable. Thanks for filing an issue anyway!
