### ISSUE TITLE
Configuration crawler.supportedMimeTypes not working

### ISSUE THREAD

**Issue by geramy92** [cgiffard/node-simplecrawler#333]
## What happened?

If I try using crawler.supportedMimeTypes the crawler crashes with an issue (see at the end of this post)
## What should have happened?

it should work :)
## Steps to reproduce the problem

```
let crawler = new Crawler(url);
crawler.supportedMimeTypes = ["text/html"];
crawler.start();
```

Error:

> (...)\node_modules\simplecrawler\lib\crawler.js:715
>         return mimeCheck.test(mimetype);
>                          ^
> 
> TypeError: mimeCheck.test is not a function
>     at (...projectpath...)\node_modules\simplecrawler\lib\crawler.js:715:26
>     at Array.some (native)
>     at Crawler.mimeTypeSupported ((...projectpath...)\node_modules\simplecrawler\lib\crawler.js:714:39)
>     at (...projectpath...)\node_modules\simplecrawler\lib\crawler.js:1518:29
>     at FetchQueue.update ((...projectpath...)\node_modules\simplecrawler\lib\queue.js:226:9)
>     at emitFetchComplete ((...projectpath...)\node_modules\simplecrawler\lib\crawler.js:1491:27)
>     at (...projectpath...)\node_modules\simplecrawler\lib\crawler.js:1577:21
>     at FetchQueue.update ((...projectpath...)\node_modules\simplecrawler\lib\queue.js:226:9)
>     at IncomingMessage.processReceivedData ((...projectpath...)\node_modules\simplecrawler\lib\crawler.js:1534:27)
>     at emitNone (events.js:91:20)

**Comment by geramy92** [comment]
Oh I found the problem. It was my Issue: I am using there a string instead of RegEx. If that is correct it is working. I think anyways there should maybe a check for that instead crashing with such an error.

**Comment by fredrikekelund** [comment]
Hey, thanks for filing an issue! You're probably right that it'd make life a bit easier for people if we allowed strings in `Crawler#supportedMimeTypes` besides just RegExp's. You're welcome to submit a PR if you like, otherwise I hope to be able to write a fix for this within a week or two!
