### ISSUE TITLE
NPM release wrong source

### ISSUE THREAD

**Issue by bymaximus** [cgiffard/node-simplecrawler#335]
Seems latest NPM simplecrawler release doesnt contain #288 changes, can you confirm?

**Comment by fredrikekelund** [comment]
Hey, thanks for filing an issue! I don't believe there's any difference between the source at GitHub and npm ATM, but #288 was never merged. Is there a particular problem you're experienced that you believe is related to that PR?

**Comment by fredrikekelund** [comment]
I'm closing this for now, let us know if you're experiencing any specific issues @bymaximus
