### ISSUE TITLE
Missing installation instruction in document

### ISSUE THREAD

**Issue by boylove142** [cgiffard/node-simplecrawler#337]
Something like this:
```
npm install --save simplecrawler
```

Although I managed to figure out the name, it's just a weird to not have one in the document.

**Comment by fredrikekelund** [comment]
Hey, thanks for filing an issue and letting us know your preference! I am personally not too fond of installation instructions like that in the README, though. I know they're fairly common, and I can see that it can be a bit confusing with the repo being named node-simplecrawler and the package being named simplecrawler, but I still think they're a bit overly verbose. Especially seeing as more or less the same command is shown pretty high up in the right column of the package page on npm, and we link to that page with a badge directly under the heading in the README.
