### ISSUE TITLE
After "freeze" / "defrost" logic crawler suddenly stops and "complete" event is never triggered

### ISSUE THREAD

**Issue by gorbatenkov** [cgiffard/node-simplecrawler#339]
Hello, thanks for the great crawler and sorry my poor English.

## What happened?
After "freeze" / "defrost" logic crawler suddenly stops and "complete" event is never triggered

## What should have happened?
Crawling process should finish with the "complete" event after "freeze" / "defrost" logic

## Steps to reproduce the problem
Use "freeze" / "defrost" logic

## My explanation
FetchQueue.prototype.defrost function use Math.max(queue._oldestUnfetchedIndex, i) and set queue._oldestUnfetchedIndex. 
For example, if  "freeze" queue consist of 4 items: "downloaded, queued, queued, queued" it will return queue._oldestUnfetchedIndex = 3. Then two previous "queued" items will be lost forever and "complete" event will never be triggered with (completeCount === length) statement. 

## My suggestion
Use Math.min(self.oldestUnfetchedIndex, index) logic  as in previous versions with "defrost" function

## Tmp solution
Use queue._oldestUnfetchedIndex = 0 in "defrost" function callback

**Comment by civalin** [comment]
I got the same problem. PR sended :D

**Comment by fredrikekelund** [comment]
Thanks for the report @gorbatenkov, this was a silly mistake on my part! I've merged @civalin's PR and am updating the test suite. Will release a new version on npm shortly as well!
