### ISSUE TITLE
Need help with crawler script to fetch 404s

### ISSUE THREAD

**Issue by shekarls** [cgiffard/node-simplecrawler#341]
Hi,
   I have tried writing some below code to mainly fetch 404/500 broken links from the page.
I'm not sure how to get everything working in this piece of code, would greatly appreciate for your inputs.

```js
function runCrawler(baseUrl) {


        var crawler = new Crawler(baseUrl);

        console.log('==============================current url: ', baseUrl);

        var failedLinks = [];

        crawler.interval = 5;
        crawler.maxDepth = 2;
        crawler.allowInitialDomainChange = true;


        crawler.on("fetchcomplete", function (queueItem) {
           
             if (queueItem.stateData.code != 200) {
                 console.log(queueItem.url + ' - ' + queueItem.stateData.code);
                 failedLinks.push(queueItem.url + ' - ' + queueItem.stateData.code);
             }

            console.log('fetchcomplete HERE.... ');
            return deferred.fulfill();

        });


        crawler.on("complete", function () {

           console.log(failedLinks);
           deferred.reject(failedLinks);
        

        });

        crawler.start();

        return deferred;
    }
```

I'm assuming the tool would fetch all Urls like 301/302/404 etc and store into my failedLinks array for my further usage.

**Comment by fredrikekelund** [comment]
Hi, thanks for using simplecrawler! If you're looking to get ahold of errant pages, like 404's and 500's, then you'll want to listen for the `fetch404`, `fetch410` and `fetcherror` events. `fetchcomplete` will only fire for resources that returned an OK status. I can see how the docs aren't super clear on this point, might be worth a clarification.
