### ISSUE TITLE
Add support for node 7.x series

### ISSUE THREAD

**Issue by fredrikekelund** [cgiffard/node-simplecrawler#342]
We should add it to the "Node Support Policy" section of the README and to the CI.

**Comment by fredrikekelund** [comment]
Actually, the node 0.12 series will stop recieving LTS updates as of 31 December, so maybe we should remove support for that in the same go.

**Comment by cgiffard** [comment]
I figure we remove support for older and unsupported versions as we need to in order to introduce new features (unless you can see reasons to do this now.) But yeah, we should add node 7.x. I'll do it now!

**Comment by cgiffard** [comment]
Added CI testing stages for 7.x, and mentioned it in the README. If you think we should remove 0.10 and 0.12 (maybe we should remove 5.x too and stick totally to the node foundation support policy?) please just do so. :)
