### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by fartbagxp** [cgiffard/node-simplecrawler#343]
The license information at the very bottom of the `README` looks to be based on the MIT license (I can't be sure though).

I was wondering if it is possible for you guys to add a LICENSE file to confirm which license you're using.

Thanks!

**Comment by cgiffard** [comment]
[It's BSD 2-Clause](https://github.com/cgiffard/node-simplecrawler/blob/master/package.json#L11), but happy to clarify that with a file.
