### ISSUE TITLE
npm install directive not included in readme

### ISSUE THREAD

**Issue by pheeque** [cgiffard/node-simplecrawler#347]

**Comment by fredrikekelund** [comment]
Hi! This issue was brought up in #337 and at that time we chose not to include it. We're always open to feedback however, so if you have a good argument to include it, you might make us rethink it

**Comment by pheeque** [comment]
I guess i feel the npm instruction is one of those things you are tuned to look for when you discover a new project. 

Keep in mind that its also discoverable via google. Some of us might not have seen the npm page itself. Much like the other issue, I really just took a stab in the dark and tried what I felt was the package name.

**Comment by fredrikekelund** [comment]
@pheeque fair enough! I've gone ahead and added it to the README :)
