### ISSUE TITLE
stripQuerystring for specific params

### ISSUE THREAD

**Issue by geramy92** [cgiffard/node-simplecrawler#348]
Hey there,
is it possible somehow, to define that only specific parameters are stripped out?

To explain it here an example:
If the link on a page is **http://example.com/index.php?page=abc** and there is a edit button with a link that is named **http://example.com/index.php?page=abc&action=edit** then either it crawls this page two times or if I set strip out querystring it will also not reached this page because the real link is in the query too (that example is from a wiki system).  Now it would be nice to say, only strip out the querystring "action"

**Comment by fredrikekelund** [comment]
Hey, @geramy92! For scenarios like these, the best thing to do is to replace the `crawler.discoverResources` method. That method is designed to be able to be replaced, so you're not breaking anything by doing so.

In this case, I'd user the cheerio module to conveniently select all elements that I'm interested in (maybe it's just `<a>` elements with an `href` attribute) and extract the relevant HTML attributes from them. Then I'd map over the extracted URLs and use the standard url module to remove the action parameter from the query string of the URL. Lastly, you simply return that array of URLs - don't bother checking for duplicates etc, simplecrawler already does that outside of the `crawler.discoverResources` method. 

There are more details in the README about how to write a custom discoverResources method as well.

**Comment by fredrikekelund** [comment]
Closing this for now. Let me know if you need any more assistance with this @geramy92
