### ISSUE TITLE
Respecting a specific bot rules in robots.txt

### ISSUE THREAD

**Issue by coderingo** [cgiffard/node-simplecrawler#349]
Hi,

Thanks for such an amazing library. I have a question and I hope to get some answers or suggestions. Is there any way to set the robots option to obey rules which are specified for a specific bot? For example. if I want to crawl all the pages that are allowed for the Google but disallowed for other bots? 

I can contribute to a pull request too if the owners are happy and guide me a little bit for the start.  I think it will be a nice option to specify a user-agent/bot name as value to  `crawler.respectRobotsTxt` which can be used to pull the rules for that specific bot instead of just true. 

Kind regards,

**Comment by fredrikekelund** [comment]
Hi @coderingo, thanks for reporting an issue! We use the excellent robots-parser module for checking sitemap rules. That module supports user-agent specific rules, and we do actually pass simplecrawler's user agent to it when checking if a particular URL is allowed. So what you can do in this case is simply change the `crawler.userAgent` property to that of Google or or whatever. Keep in mind that the website you're crawling will also see the same user agent, there's no setting to keep those two separate right now.

**Comment by fredrikekelund** [comment]
Not at the moment, no. If you do need to separate them, I'd urge you to write a custom fetch condition. Just fetch the robots.txt before starting the crawler, use [robots-parser](https://www.npmjs.com/package/robots-parser) to parse it, and add a fetch condition that calls `robotsParserInstance.isAllowed` with the user agent you want to check for.

**Comment by coderingo** [comment]
Okay thank you, That can fix my case 👍
