### ISSUE TITLE
Inconsistent Variable Value in Download condition.

### ISSUE THREAD

**Issue by coderingo** [cgiffard/node-simplecrawler#354]
Hi, 

I just stumbled upon a strange problem. I have a download condition where I check the `queueItem` with another object which I create outside of the download function. For debugging purpose, I logged that object to console and I saw that it was giving `undefined` value at random. I then checked it with a const variable and the result was same. The `addDownloadConition` does not get the variable sometime. A simplified version of my code is like this:

```
 //startCrawler.js
 const Crawler = require('simplecrawler');

 //Initial data is an object with initial.url set to url for crawling     

 const startCrawler = function startCrawler(initialData) {
      const crawler = new Crawler(initialData.url);
          crawler.start();

 const randomVariable = "set";
 const downloadCondition = crawler.addDownloadCondition((queueItem) => {
     console.log(randomVariable);
  });
};
```
Following is my console log set for the above code:

`set
set
set
set
set
set
undefined
set
set
undefined
undefined
set`

I am using version `1.0.5` on node 6. I updated recently from a lower version. I guess maybe something is changed in the new version. I didn't found anything helpfull regarding this in the release logs.  I want to know if there is any way possible to keep the variable consistent for each request to the download condition. 

Thank You

**Comment by coderingo** [comment]
Even the passed `queueItem` is undefined.  I did this:
```
const downloadCondition = crawler.addDownloadCondition((queueItem,response) => {
   if(!queueItem){
      console.log(queueItem);
    }
  });
```
And Got this:

```
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
```

I hope its something wrong on my side but even the queueItem is undefined.

**Comment by coderingo** [comment]
Tested on 1.0.3 as well, Still the same problem

**Comment by coderingo** [comment]
Version 1.0.3 is no longer showing the same behavior. I only got undefined once when doing a lot of simultaneous requests but after that I didn't got any error. My bad, shouldn't have moved beyond the latest release.

**Comment by fredrikekelund** [comment]
Hi, @coderingo – I tested the code you supplied in your first comment and let the crawler run for about 5 minutes, but wasn't able to reproduce the problem. Could you try to reduce your code to a reproducible test case? I kind of suspect that this is a problem somewhere else in your code, but creating a test case might help narrow down the issue wherever it's located!

**Comment by coderingo** [comment]
Hi @fredrikekelund , 

I still  didn't got that error again, maybe it was something wrong on my end
