### ISSUE TITLE
How to Keep Listening to events after crawler is stopped

### ISSUE THREAD

**Issue by coderingo** [cgiffard/node-simplecrawler#359]
Hi,

I am doing a lot of async work inside the `fetchComplete` event. Unfortunately when the crawler stops, All the processes inside the event also dies. Is there any way to let the crawler complete the tasks in events before closing everything at once?

**Comment by fredrikekelund** [comment]
Hi @coderingo! The node process shouldn't terminate before all work is done, including any async operations in progress, and simplecrawler doesn't do anything to exit the process either. Could you provide a code sample demonstrating your problem?

**Comment by fredrikekelund** [comment]
Closing this issue since it hasn't been active in a while. Feel free to re-open it if you're still having trouble, @coderingo!
