### ISSUE TITLE
avoid add to queue

### ISSUE THREAD

**Issue by bymaximus** [cgiffard/node-simplecrawler#362]
Not a issue but a question, it is possible to avoid add discovered resources to queue if queue has X pending items, but not ignore the new found items instead wait until queue get reduced to continue.

Like a pause but at queue not at crawler itself, if queue currently have 100 pending items it will not add new discovered resources and wait until queue get less than 100 items to then add it.

The point is to not run 'discoverResources' function if queue full but not ignore it, process it once queue gets 'free'

**Comment by cgiffard** [comment]
Hey — thanks for stopping in. It's always good to hear feedback.

What you're describing seems to me like a second queue, for the queue. I'm curious to hear your use case for this — is there a reason why you don't want the queue to grow longer than 100 items?

**Comment by bymaximus** [comment]
Hi, yes, reason is for example when using cherrio to parse page code, if a page have big content and the running queue (request being completed) also find pages with big content it makes a big cpu usage when parsing all these big pages same time.

So, I was thinking to when queue hits some number it will not add new found items to queue until queue items finish processing or queue hit some other small value to then add items found to queue again

**Comment by cgiffard** [comment]
You can always write a wrapper around `discoverResources` which performs this behaviour for you, but at this stage I don't think we've got any immediate intention to support functionality like that. Let me know if you'd like me to point to where you could hook in. :)

**Comment by bymaximus** [comment]
Hi, yes, I did it, thanks.
