### ISSUE TITLE
Asynchronous event listeners not waiting

### ISSUE THREAD

**Issue by claflamme** [cgiffard/node-simplecrawler#372]
## What happened?

I tried calling `this.wait()` inside of a handler for the 'fetchcomplete' event, [as explained here](https://github.com/cgiffard/node-simplecrawler#waiting-for-asynchronous-event-listeners). The crawler continued on without waiting. I'm using v1.1.1.

## What should have happened?

I expected the crawler to pause while some async processing took place, then continue when the function returned by `this.wait()` was invoked (or 10 seconds passed).

## Steps to reproduce the problem

This code seems to reproduce the problem I was having. If you look at the console while running it, it gets flooded with URLs.

```js
const Crawler = require('simplecrawler');

const crawler = Crawler('https://google.com');

crawler.on('fetchcomplete', function(queueItem, data, res) {
  const resume = this.wait();
  console.log(queueItem.url)
});

crawler.start();
```

**Comment by cgiffard** [comment]
Hi Cory — thanks for filing an issue!

The purpose of the `wait` method is not to halt all other operations in process, but to prevent the crawler from completing and terminating the crawl, if you're still waiting on the results of an asynchronous operation to, for example, add some items to the queue (which would continue the crawl, even if the current queue is exhausted.)

The documentation for this method could be a bit clearer, but it does say:

> Sometimes, you might want to wait for simplecrawler to wait for you while you perform some asynchronous tasks in an event listener, instead of having it racing off and firing the complete event, halting your crawl. For example, if you're doing your own link discovery using an asynchronous library method.

I am curious to hear about your use case though — I might be able to assist you to solve it a different way.
