### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by Vittoriourzi** [cgiffard/node-simplecrawler#384]
Hello!, congratulation for your spider! It's awesome!
I'm trying to scrape http://compagniadellabellezza.com but your crawler wasn't able to crawl it.
The event triggered was  "robotstxterror" but the robots.txt file is OK (status code 200 and valid robots).
I tried to crawl ignoring robots using respectRobotsTxt=false;  but the crawler got me the same error.  

PS. if i set respectRobotsTxt=true the crawler trigger the event 'robotstxterror' but with this error:
```
{ Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at Socket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }

```
 
ps ps. i found this bug also on https://www.murgo.it/  (but this website had an invalid robots.txt)

**Comment by konstantinblaesi** [comment]
@Vittoriourzi I can crawl these pages just fine with
```
const Crawler = require("./lib/crawler");

let crawler = (new Crawler("https://www.murgo.it/"))
    .on("fetchcomplete", function () {
        console.log("Fetched a resource!");
    });
crawler.maxDepth = 2;
crawler.start();
```

Afaik `socket hang up` usually means you are running into a connection timeout for some reason (firewall, proxy, server cannot handle the load).

Can you provide a snippet that reproduces the problem along with information about the environment you are running the crawler in?

**Comment by Vittoriourzi** [comment]
@konstantinblaesi,  You right. fixed for me. (But i don't know if is a correct flow for this case)
In this case, this error appears when i setted the crawler.userAgent like this:
`crawler.userAgent='Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)';`
Maybe these website using a userAgent bot controll that not allow me to crawling.. 
If i crawling the same website using this user agent :
`crawler.userAgent="Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36";`
It's works fine! (Maybe a generic error event emitter for this case will be useful.. )
Cheers!

**Comment by cgiffard** [comment]
That suggests to me that the site you're using is directly blocking requests pretending to be GoogleBot from non-Google IPs using a Web Application Firewall or similar infrastructure. I'll take the bubbling up of the error to the generic listener under advisement. Maybe that's a new feature we could consider (though generally speaking I'd prefer to keep the listeners fairly specific for now.)
