### ISSUE TITLE
Good crawler behaviour...

### ISSUE THREAD

**Issue by WAINGOR** [cgiffard/node-simplecrawler#390]
Hi all,

 I have made a crawler that I intend to let keep track of about 10 specific pages on 1 website during the whole day. I would like to let it make one request every minute per page. What would be good settings (maxConnections/requests per second) so my IP address wont get blocked by this specific website? 

Greets

**Comment by cgiffard** [comment]
It really depends entirely on the site — larger sites will be architected to accomodate more traffic. It also depends on how frequently you need to be updated — if you've got to know about a change in under ten seconds, you wouldn't set the crawl loop interval to a minute per request, for instance.

For small, bandwidth sensitive sites, I'd definitely recommend opening no more than a single concurrent connection, and trying to keep traffic below about five requests per second. (Maybe even less if you're intending to make that a constant polling interval for an indefinite period of time.)

If in doubt, you should ask the site owners — they'll have the best idea of what they're prepared to accept.

**Comment by WAINGOR** [comment]
Hi cgiffard, thank you for taking your time in answering this question, it was quite helpful. Greets
