### ISSUE TITLE
Correct Cache API Pattern

### ISSUE THREAD

**Issue by cgiffard** [cgiffard/node-simplecrawler#4]
At the moment, the callback is passed a single parameter, which could be `null` (if an item doesn't exist) or an actual value.

To fit better with node's internal patterns, the first parameter should be an error (or `null`), and the second parameter should be the result.

**Comment by fredrikekelund** [comment]
Is this still applicaple @cgiffard?

**Comment by cgiffard** [comment]
The cache /is/ a pile of crap, and it would be nice to make it not a pile of crap, haha. :P

It's kinda sad how long I've let this one linger. *hangs head in shame*

**Comment by cgiffard** [comment]
It would be nice if the cache tied in with etags, though perhaps that's a different issue.

**Comment by fredrikekelund** [comment]
Haha I see.. I haven't actually used the cache, so I haven't seen how bad it is. Can we use a third party module for help with this?

**Comment by cgiffard** [comment]
Cache manager has been good, but it's really solving a different problem to the one we're trying to manage here. I think cleaning up the API based on a reference implementation might be a good way to work — I'll try make a redis-backed backed cache at some point soon, and might have some thoughts.

**Comment by cgiffard** [comment]
Closing as this is totally ancient. If we get complaints we should revisit the cache, but I figure it's fine to leave it for now.
