### ISSUE TITLE
how convert the response body to utf8 please

### ISSUE THREAD

**Issue by luxueyan2008** [cgiffard/node-simplecrawler#45]
is it supported the feature?
as the node-crawler https://github.com/sylvinus/node-crawler
forceUTF8: Boolean, if true will try to detect the page charset and convert it to UTF8 if necessary. Never worry about encoding anymore! (Default false),

**Comment by cgiffard** [comment]
I use iconv in BAS, and I've had nothing but pain, so I'd prefer not to include it here. Ultimately you can choose to bind against iconv in your own project.
