### ISSUE TITLE
Default cookie's domain

### ISSUE THREAD

**Issue by leeroybrun** [cgiffard/node-simplecrawler#75]
If the domain is not set by the server, the cookie's domain will be defined to * (default value). But when it resend the cookies, it will not resend this one because it does not match the domain.

This is just a small error, I think we just need to be able to get the domain from where the cookie was sent. We need to pass this domain from Crawler.handleResponse to CookieJar.addFromHeaders and then to Cookie.fromString to use it if the domain in the cookie is not set.

I was thinking, why are you not using a module like "tough-cookie" ? It's used by the "request" module and is compliant with RFC6265.

This will add a dependency, but it's a small one. And this will take cookies' logic out of this module.

Best regards,

Leeroy

**Comment by fredrikekelund** [comment]
This was addressed in #200. Maybe using tough-cookie is a good choice, but at least the problem that was the start of this thread should be fixed by now
