### ISSUE TITLE
The way to search the base url only 

### ISSUE THREAD

**Issue by fairul82** [cgiffard/node-simplecrawler#80]
Hi cgiffard,
Thanks for sharing this wonderful app. It helps me a lot. I just want to check if there is anyway I can search for URL for the html pages only ? For an example , I would like the following;

www.test.com
www.test.com/page1
www.test.com/page2

But , I want to exclude the search up to the resource level;
www.test.com/page1/*.jpg
www.test.com/page1/*.css
www.test.com/page1/*.js

**Comment by cgiffard** [comment]
Hi — apologies for the terrible delay in getting back to you. In order to do this, you'll best use a fetchCondition. This is documented under ['excluding certain resources from downloading'.](https://github.com/cgiffard/node-simplecrawler#excluding-certain-resources-from-downloading)
