### ISSUE TITLE
Fetcherror is emitted with variable set of parameters

### ISSUE THREAD

**Issue by aleksika** [cgiffard/node-simplecrawler#81]
Fetcherror event is emitted with variable set of parameters. On line 
https://github.com/cgiffard/node-simplecrawler/blob/master/lib/crawler.js#L553 it is emitted as crawler.emit("fetcherror",queueItem);
and on line https://github.com/cgiffard/node-simplecrawler/blob/master/lib/crawler.js#L991 as crawler.emit("fetcherror",queueItem,response);
Listening to fetcherror event could then potentially lead to crawl not completing as described in issue #48.

**Comment by cgiffard** [comment]
Split this into two events — `fetcherror` and `gziperror`. Will publish shortly with updated docs. :)

**Comment by cgiffard** [comment]
Fixed in #5bb5c24 :)
