### ISSUE TITLE
downloadUnsupported flag not functional

### ISSUE THREAD

**Issue by mlakhia** [cgiffard/node-simplecrawler#89]
It would be awesome to utilize the boolean option ```downloadUnsupported```. I've poked through the source and don't see the flag being used at all.

Currently I'm using ```addFetchCondition``` in it's place, but as the downloadUnsupported option is documented, shouldn't it be functional?

**Comment by cgiffard** [comment]
It's functional now! The benefit of using this check is you can use the returned mime type from a request (ie. the file extension on a URL might be `.php`, but still return an image.) Now, `crawler.downloadUnsupported` will close the socket of an unsupported mime type if set to false.
