### ISSUE TITLE
Post requests?

### ISSUE THREAD

**Issue by rclai** [cgiffard/node-simplecrawler#91]
Is it possible to do post requests with this?

**Comment by fredrikekelund** [comment]
I think we should add an FAQ item to the README about crawling sites that require a login to solve this issue.

My proposed solution would that the developer firstly makes a POST request to the login endpoint (using either the http module directly, or something like [request](https://npmjs.com/package/request)), and then manually adds the cookie returned in the server's response to simplecrawler cookie jar. I don't see a case where a regular site would need to be crawled with all POST requests.

**Comment by cgiffard** [comment]
Yeah, crawling with POST requests doesn't seem practical to me. But the ability to make a post request in the context of the crawler (to log in, etc.) seems sensible. Perhaps we should expose a `crawler.post` function, which takes a URL and a payload?

(Just a thought. The counterpoint to that, is of course, the additional complexity incurred, for not much additional utility.)

**Comment by fredrikekelund** [comment]
It could of course be useful for developers to not have to use a separate module to do this, but I'm a bit skeptic right off the bat. If we were to add a method like that, do you think we could rely on the normal fetch events for passing the response back to the dev?

Might make more sense if we renamed `crawler.fetchQueueItem` `crawler.get` instead, and both of them would fire the same events etc (but `crawler.get` would be the only one used by the crawler normally)

**Comment by cgiffard** [comment]
I'd be inclined to leave it as an auxiliary method for now. I think let's keep it as a thought exercise for post-V1, but I think it needs architectural fleshing out before we run off and add it.

**Comment by fredrikekelund** [comment]
Alright, let's add a FAQ item to the README for now then and close this ticket once that's done

**Comment by fredrikekelund** [comment]
Added what we discussed earlier about crawling sites that require a login to the README. I think that abstracting the HTTP request logic would make sense as a goal, but closing this ticket for now, we can discuss that in another thread
